# Generated by Django 2.2.28 on 2024-03-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helevents', '0005_auto_20231212_1048'),
        ('helevents', '0005_auto_20240215_1520'),
    ]

    operations = [
    ]
