# Generated by Django 3.2.23 on 2023-12-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_orghierarchy", "0011_alter_datasource_user_editable_organizations"),
        ("helevents", "0006_user_registration_admin_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="financial_admin_organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="financial_admin_users",
                to="django_orghierarchy.Organization",
            ),
        ),
    ]
