# Generated by Django 5.2.6 on 2025-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helevents", "0008_serializablepublisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
