# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20151129_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_language',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Language', verbose_name='In language'),
        ),
    ]
