# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_add_in_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='event_images', verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Cropping')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventImage_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventImage_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='place',
            managers=[
                ('geo_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='external_image_url',
        ),
        migrations.AlterField(
            model_name='organization',
            name='admin_users',
            field=models.ManyToManyField(blank=True, related_name='admin_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventImage', verbose_name='Event image'),
        ),
    ]
