# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_add_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='audience',
        ),
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.ManyToManyField(blank=True, related_name='audiences', to='events.Keyword'),
        ),
    ]
