# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_auto_20160113_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('url', models.URLField(max_length=400, verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Cropping')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventImage_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventImage_last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Published_images', to='events.Organization', verbose_name='Publisher')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='external_image_url',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='keywordset',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Image', verbose_name='Image'),
        ),
    ]
