# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20160205_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Published_images', to='events.Organization', verbose_name='Publisher'),
        ),
    ]
