# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20160205_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Image'),
        ),
    ]
