# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 12:32
from __future__ import unicode_literals

from django.db import migrations
import mptt
import mptt.managers

def _add_mptt_manager(cls):
    manager = mptt.managers.TreeManager()
    manager.model = cls
    mptt.register(cls, parent_attr='super_event')
    manager.contribute_to_class(cls, 'objects')

def external_image_url_to_image_url(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Image = apps.get_model("events", "Image")

    _add_mptt_manager(Event)

    for event in Event.objects.filter(external_image_url__isnull=False):
        url = event.external_image_url
        image_object = Image.objects.create(url=url)
        event.image = image_object
        event.external_image_url = None
        event.save()

def image_url_to_external_image_url(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Image = apps.get_model("events", "Image")

    _add_mptt_manager(Event)

    for event in Event.objects.filter(image__url__isnull=False).filter(image__image__exact=''):
        url = event.image.url
        event.external_image_url = url
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20160208_1729'),
    ]

    operations = [
        migrations.RunPython(external_image_url_to_image_url, image_url_to_external_image_url),
    ]
