# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_move_legacy_event_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='external_image_url',
        ),
    ]
