# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_external_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
