# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 16:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20160229_2111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='place',
            managers=[
                ('geo_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
