# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20160506_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
