# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_initial_licenses(apps, schema_editor):
    License = apps.get_model('events', 'License')

    License.objects.create(
        id='event_only',
        name_fi='Vain tapahtuman markkinointiin',
        name_sv='Endast för marknadsföring av evenemanget',
        name_en='For event marketing only',
        url='',
    )

    License.objects.create(
        id='cc_by',
        name_fi='Nimeä 4.0 Kansainvälinen (CC BY 4.0)',
        name_sv='Erkännande 4.0 Internationell (CC BY 4.0)',
        name_en='Attribution 4.0 International (CC BY 4.0)',
        url='https://creativecommons.org/licenses/by/4.0/',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_add_deleted_field_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_fi', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_sv', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url', blank=True)),
            ],
            options={
                'verbose_name_plural': 'Licenses',
                'verbose_name': 'License',
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AddField(
            model_name='image',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.License', verbose_name='License', default='cc_by'),
        ),
        migrations.RunPython(create_initial_licenses, migrations.RunPython.noop)
    ]
