# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 13:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_add_license_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='custom_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url',
            field=models.URLField(blank=True, default='', verbose_name='Place home page'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url_en',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Place home page'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url_fi',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Place home page'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url_sv',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Place home page'),
        ),
    ]
