# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_minor_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Event home page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_url_en',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Event home page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_url_fi',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Event home page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_url_sv',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Event home page'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='info_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Web link to offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='info_url_en',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Web link to offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='info_url_fi',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Web link to offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='info_url_sv',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Web link to offer'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Place home page'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url_en',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Place home page'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url_fi',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Place home page'),
        ),
        migrations.AlterField(
            model_name='place',
            name='info_url_sv',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Place home page'),
        ),
    ]
