# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20160819_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photographer_name',
            field=models.CharField(null=True, blank=True, max_length=255, verbose_name='Photographer name'),
        ),
    ]
