# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-27 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_make_api_key_non_nullable'),
        ('events', '0028_add_photographer_name'),
    ]

    operations = [
    ]
