# Generated by Django 1.9.13 on 2017-07-11 10:14

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0039_add_user_editable_to_datasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="admin_orgs",
            field=models.ManyToManyField(
                blank=True,
                related_name="_organization_admin_orgs_+",
                to="events.Organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="level",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="lft",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="events.Organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="rght",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
