# Generated by Django 1.9.13 on 2017-08-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0041_rebuild_organization_mptt_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="replaced_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="events.Place",
            ),
        ),
    ]
