# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_rebuild_organization_mptt_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='replaced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='events.Place'),
        ),
    ]
