# Generated by Django 1.11.5 on 2017-09-15 14:57

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helevents", "0003_auto_20170915_1529"),
        ("events", "0043_add_publisher_to_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKeyUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="events.DataSource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("helevents.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="place",
            managers=[],
        ),
    ]
