# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:53
from __future__ import unicode_literals

from django.db import migrations


def migrate_org_data(apps, schema_editor):
    event_org_model = apps.get_model('events', 'Organization')
    new_org_model = apps.get_model('django_orghierarchy', 'Organization')

    for org in event_org_model.objects.all():
        origin_id = org.origin_id or org.id.split(':')[-1]

        new_org = new_org_model.objects.create(
            id=org.id,
            data_source_id=org.data_source_id,
            name=org.name,
            origin_id=origin_id,
            created_by_id=org.created_by_id,
            last_modified_by_id=org.last_modified_by_id,
            parent_id=org.parent_id,
            level=org.level,
            lft=org.lft,
            rght=org.rght,
            tree_id=org.tree_id,
        )

        new_org.admin_users = org.admin_users.all()


def clean_org_data(apps, schema_editor):
    new_org_model = apps.get_model('django_orghierarchy', 'Organization')
    new_org_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_rename_org_admin_users_related_name'),
    ]

    operations = [
        migrations.RunPython(migrate_org_data, clean_org_data)
    ]
