# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_migrate_organization_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_systems', to='django_orghierarchy.Organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_events', to='django_orghierarchy.Organization', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='image',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Published_images', to='django_orghierarchy.Organization', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Published_keywords', to='django_orghierarchy.Organization', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='keywordset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_orghierarchy.Organization', verbose_name='Organization which uses this set'),
        ),
        migrations.AlterField(
            model_name='place',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_orghierarchy.Organization', verbose_name='Publisher'),
        ),
    ]
