# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0047_alter_org_fk_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="admin_orgs",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="admin_users",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="image",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="parent",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
