# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0054_add_chinese_russian_and_arabic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="description_zh",
            new_name="description_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="headline_zh",
            new_name="headline_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="info_url_zh",
            new_name="info_url_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="location_extra_info_zh",
            new_name="location_extra_info_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="name_zh",
            new_name="name_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="provider_zh",
            new_name="provider_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="secondary_headline_zh",
            new_name="secondary_headline_zh_hans",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="short_description_zh",
            new_name="short_description_zh_hans",
        ),
        migrations.RenameField(
            model_name="keyword",
            old_name="name_zh",
            new_name="name_zh_hans",
        ),
        migrations.RenameField(
            model_name="keywordset",
            old_name="name_zh",
            new_name="name_zh_hans",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="name_zh",
            new_name="name_zh_hans",
        ),
        migrations.RenameField(
            model_name="license",
            old_name="name_zh",
            new_name="name_zh_hans",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="description_zh",
            new_name="description_zh_hans",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="info_url_zh",
            new_name="info_url_zh_hans",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="price_zh",
            new_name="price_zh_hans",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="address_locality_zh",
            new_name="address_locality_zh_hans",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_zh",
            new_name="description_zh_hans",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="info_url_zh",
            new_name="info_url_zh_hans",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="name_zh",
            new_name="name_zh_hans",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="street_address_zh",
            new_name="street_address_zh_hans",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="telephone_zh",
            new_name="telephone_zh_hans",
        ),
        migrations.AlterField(
            model_name="language",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        # Since we change language id field, we need to update ForeignKey links
        # https://code.djangoproject.com/ticket/25012
        migrations.RunSQL(
            "ALTER TABLE events_keywordlabel ALTER COLUMN language_id TYPE varchar(10);"
        ),
        migrations.RunSQL(
            "ALTER TABLE events_eventlink ALTER COLUMN language_id TYPE varchar(10);"
        ),
        migrations.RunSQL(
            "ALTER TABLE events_event_in_language ALTER COLUMN language_id TYPE varchar(10);"
        ),
    ]
