# Generated by Django 1.11.11 on 2018-06-06 12:09

from django.db import migrations


def make_many_images(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    for event in Event.objects.all():
        if event.image:
            event.images.add(event.image)


def make_one_image(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    for event in Event.objects.all():
        if event.images.first():
            event.image = event.images.first()
            event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0058_add_multiple_images_to_event"),
    ]

    operations = [
        migrations.RunPython(make_many_images, make_one_image),
    ]
