# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-25 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0059_migrate_event_image_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
    ]
