# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0060_delete_single_image_from_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="super_event_type",
            field=models.CharField(
                blank=True,
                choices=[("recurring", "Recurring"), ("umbrella", "Umbrella event")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
