# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0061_add_umbrella_super_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="super_event_type",
            field=models.CharField(
                blank=True,
                choices=[("recurring", "Recurring"), ("umbrella", "Umbrella event")],
                db_index=True,
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
