# Generated by Django 2.2.9 on 2020-01-31 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0071_event_replaced_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aliases",
                to="events.Event",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aliases",
                to="events.Keyword",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aliases",
                to="events.Place",
            ),
        ),
    ]
