# Generated by Django 2.2.9 on 2020-02-04 10:04
from django.contrib.auth.management import create_permissions
from django.db import migrations, transaction
from django.db.utils import IntegrityError


def force_create_required_permissions(apps):
    """
    Create permissions for helevents (User) and django_orghierarchy app.

    Required because django creates permissions only after all migrations
    have been applied and this migration depends on django_orghierarchy
    permissions.
    """
    for app_config in apps.get_app_configs():
        if app_config.name in ["helevents", "django_orghierarchy"]:
            # app_config is of type AppConfigStub and does not
            # contain models_module attribute naturally
            app_config.models_module = True
            create_permissions(app_config)
            app_config.models_module = None


def create_light_admin_group(apps):
    force_create_required_permissions(apps)

    Group = apps.get_model("auth", "Group")  # noqa
    Permission = apps.get_model("auth", "Permission")  # noqa

    try:
        # If "Light Admins" already exists, migration causes
        # django.db.transaction.TransactionManagementError
        # without transaction.atomic().
        with transaction.atomic():
            light_admin_group = Group.objects.create(name="Light Admins")
    except IntegrityError:
        print('\nGroup with name "Light Admins" already exists. Skipping creation.')  # noqa: T201
        return

    regular_users_perm = Permission.objects.get(
        codename="change_organization_regular_users"
    )
    view_user = Permission.objects.get(codename="view_user")
    light_admin_group.permissions.set([regular_users_perm, view_user])


def forwards(apps, schema_editor):
    create_light_admin_group(apps)


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0073_soft_delete_replaced_objects"),
        (
            "django_orghierarchy",
            "0009_add_change_organization_regular_users_permission",
        ),
        ("helevents", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
