# Generated by Django 2.2.11 on 2020-05-03 22:08

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0074_create_light_admin_group"),
    ]

    operations = [
        TrigramExtension(),
    ]
