# Generated by Django 2.2.11 on 2020-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0075_add_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterTimeLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField()),
                ('importer_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('last_run', 'importer_name')},
            },
        ),
    ]
