# Generated by Django 2.2.11 on 2020-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0075_auto_20200715_1426_squashed_0076_auto_20200717_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text_ar',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_fi',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_sv',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='image',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='image',
            name='name_fi',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='image',
            name='name_ru',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='image',
            name='name_sv',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='image',
            name='name_zh_hans',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
