# Generated by Django 2.2.11 on 2020-08-03 07:03

from django.db import migrations

def add_translated_values(apps, schema_editor):
    Image = apps.get_model('events', 'Image')
    for image in Image.objects.all():
        image.name_fi = image.name
        image.alt_text_fi = image.alt_text
        image.save()



class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_auto_20200803_1002'),
    ]

    operations = [
        migrations.RunPython(add_translated_values),
    ]
