# Generated by Django 2.2.28 on 2023-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_add_data_source_past_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
