# Generated by Django 2.2.13 on 2021-03-19 09:44
"""This migration adds language-specific tsvector columns, triggers to update them and indices
   needed for the full-text search on events_event table.
"""
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("events", "0079_add_search_vectors"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "UPDATE events_event SET search_vector_fi ="
                        "setweight(to_tsvector('finnish', coalesce(name_fi, '')), 'A') || setweight(to_tsvector('finnish', coalesce(short_description_fi, '')), 'B') || setweight(to_tsvector('finnish', coalesce(description_fi, '')), 'C');",
                        "UPDATE events_event SET search_vector_sv ="
                        "setweight(to_tsvector('finnish', coalesce(name_sv, '')), 'A') || setweight(to_tsvector('finnish', coalesce(short_description_sv, '')), 'B') || setweight(to_tsvector('finnish', coalesce(description_sv, '')), 'C');",
                        "UPDATE events_event SET search_vector_en ="
                        "setweight(to_tsvector('finnish', coalesce(name_en, '')), 'A') || setweight(to_tsvector('finnish', coalesce(short_description_en, '')), 'B') || setweight(to_tsvector('finnish', coalesce(description_en, '')), 'C');",
                        "CREATE FUNCTION events_finnish_content_trigger_function() RETURNS trigger AS $$ "
                        "begin "
                        "new.search_vector_fi := "
                        "setweight(to_tsvector('pg_catalog.finnish', coalesce(new.name_fi,'')), 'A') || "
                        "setweight(to_tsvector('pg_catalog.finnish', coalesce(new.short_description_fi,'')), 'B') || "
                        "setweight(to_tsvector('pg_catalog.finnish', coalesce(new.description_fi,'')), 'C');"
                        "return new; "
                        "end "
                        "$$ LANGUAGE plpgsql; "
                        "CREATE FUNCTION events_swedish_content_trigger_function() RETURNS trigger AS $$ "
                        "begin "
                        "new.search_vector_sv := "
                        "setweight(to_tsvector('pg_catalog.swedish', coalesce(new.name_sv,'')), 'A') || "
                        "setweight(to_tsvector('pg_catalog.swedish', coalesce(new.short_description_sv,'')), 'B') || "
                        "setweight(to_tsvector('pg_catalog.swedish', coalesce(new.description_sv,'')), 'C');"
                        "return new; "
                        "end "
                        "$$ LANGUAGE plpgsql; "
                        "CREATE FUNCTION events_english_content_trigger_function() RETURNS trigger AS $$ "
                        "begin "
                        "new.search_vector_en := "
                        "setweight(to_tsvector('pg_catalog.english', coalesce(new.name_en,'')), 'A') || "
                        "setweight(to_tsvector('pg_catalog.english', coalesce(new.short_description_en,'')), 'B') || "
                        "setweight(to_tsvector('pg_catalog.english', coalesce(new.description_en,'')), 'C');"
                        "return new; "
                        "end "
                        "$$ LANGUAGE plpgsql; "
                        "CREATE TRIGGER events_finnish_content_trigger BEFORE INSERT OR UPDATE ON events_event FOR EACH ROW EXECUTE PROCEDURE events_finnish_content_trigger_function();"
                        "CREATE TRIGGER events_swedish_content_trigger BEFORE INSERT OR UPDATE ON events_event FOR EACH ROW EXECUTE PROCEDURE events_swedish_content_trigger_function();"
                        "CREATE TRIGGER events_english_content_trigger BEFORE INSERT OR UPDATE ON events_event FOR EACH ROW EXECUTE PROCEDURE events_english_content_trigger_function();",
                    ],
                    reverse_sql=[
                        "DROP TRIGGER events_finnish_content_trigger ON events_event;"
                        "DROP FUNCTION events_finnish_content_trigger_function;"
                        "DROP TRIGGER events_swedish_content_trigger ON events_event;"
                        "DROP FUNCTION events_swedish_content_trigger_function;"
                        "DROP TRIGGER events_english_content_trigger ON events_event;"
                        "DROP FUNCTION events_english_content_trigger_function;"
                    ],
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY events_finnish_content_index ON events_event USING GIN (search_vector_fi);",
                    reverse_sql="DROP INDEX events_finnish_content_index;",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY events_swedish_content_index ON events_event USING GIN (search_vector_sv);",
                    reverse_sql="DROP INDEX events_swedish_content_index;",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY events_english_content_index ON events_event USING GIN (search_vector_en);",
                    reverse_sql="DROP INDEX events_english_content_index;",
                ),
            ]
        ),
    ]
