# Generated by Django 2.2.11 on 2021-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_event_virtualevent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_event_type',
            field=models.CharField(blank=True, choices=[('sub_recurring', 'Sub_Recurring'), ('sub_umbrella', 'Sub_Umbrella')], db_index=True, default=None, max_length=255, null=True),
        ),
    ]
