# Generated by Django 2.2.28 on 2023-12-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0079_allow_blank_as_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('origin_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Origin ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name_fi', models.CharField(blank=True, max_length=20, null=True)),
                ('name_sv', models.CharField(blank=True, max_length=20, null=True)),
                ('name_en', models.CharField(blank=True, max_length=20, null=True)),
                ('name_zh_hans', models.CharField(blank=True, max_length=20, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=20, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_hobbycategory_created_by', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_hobbycategory_data', to=settings.DJANGO_ORGHIERARCHY_DATASOURCE_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_hobbycategory_modified_by', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(limit_choices_to={'sets': 'espoo:topics'}, related_name='supercategories', to='events.Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='hobby_categories',
            field=models.ManyToManyField(blank=True, related_name='hobbies', to='events.HobbyCategory'),
        ),
    ]
