# Generated by Django 2.2.13 on 2021-04-12 19:50

from django.db import migrations, models

from linkedevents.settings import MUNIGEO_MUNI


def forwards_func(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(location__divisions__ocd_id__endswith=MUNIGEO_MUNI).update(
        local=True
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0080_populate_tsvectors_and_indices"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="local",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
