# Generated by Django 2.2.24 on 2021-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_event_sub_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enrolment_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enrolment end time'),
        ),
        migrations.AddField(
            model_name='event',
            name='enrolment_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enrolment start time'),
        ),
        migrations.AddField(
            model_name='event',
            name='maximum_attendee_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum attendee capacity'),
        ),
        migrations.AddField(
            model_name='event',
            name='minimum_attendee_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum attendee capacity'),
        ),
        migrations.AddField(
            model_name='event',
            name='type_id',
            field=models.SmallIntegerField(choices=[(1, 'General'), (2, 'Course'), (3, 'Volunteering'), (4, 'Hobbies')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience_max_age',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Maximum recommended age'),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience_min_age',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Minimum recommended age'),
        ),
    ]
