# Generated by Django 2.2.28 on 2024-03-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_auto_20231214_1351'),
        ('events', '0080_event_event_registration_link'),
    ]

    operations = [
    ]
