# Generated by Django 2.2.24 on 2021-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_auto_20210818_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enrolment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enrolment URL'),
        ),
    ]
