# Generated by Django 2.2.24 on 2021-11-02 08:05

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_event_enrolment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Name')),
                ('name_fi', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('name_sv', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('name_zh_hans', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
            ],
            bases=(models.Model, events.models.SimpleValueMixin),
        ),
        migrations.AddField(
            model_name='offer',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='paymentmethods', to='events.PaymentMethod'),
        ),
    ]
