# Generated by Django 2.2.24 on 2022-01-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_auto_20211102_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Is this keyword excluded from keyword list and set searches', verbose_name='Is hidden'),
        ),
    ]
