# Generated by Django 2.2.13 on 2021-05-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0083_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subject"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Subject"
                    ),
                ),
            ],
        ),
    ]
