# Generated by Django 2.2.13 on 2021-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0084_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="body",
            field=models.TextField(blank=True, verbose_name="Body"),
        ),
    ]
