# Generated by Django 3.2 on 2023-02-07 11:43

from django.db import migrations, models


def copy_editable_values(apps, schema_editor):
    DataSource = apps.get_model("events", "DataSource")  # noqa
    for ds in DataSource.objects.all():
        ds.user_editable_organizations = ds.user_editable_resources
        ds.save(update_fields=("user_editable_organizations",))


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0087_image_alt_text_translation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasource",
            old_name="user_editable",
            new_name="user_editable_resources",
        ),
        migrations.AlterField(
            model_name="datasource",
            name="user_editable_resources",
            field=models.BooleanField(
                default=False, verbose_name="Resources may be edited by users"
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="user_editable_organizations",
            field=models.BooleanField(
                default=False, verbose_name="Organizations may be edited by users"
            ),
        ),
        migrations.RunPython(copy_editable_values, migrations.RunPython.noop),
    ]
