# Generated by Django 3.2 on 2023-02-07 11:43

from django.db import migrations


def fix_light_admin_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")  # noqa
    Permission = apps.get_model("auth", "Permission")  # noqa

    light_admin_group, _ = Group.objects.get_or_create(name="Light Admins")
    regular_users_perm = Permission.objects.get(
        codename="change_organization_regular_users"
    )
    view_user = Permission.objects.get(codename="view_user")
    light_admin_group.permissions.add(regular_users_perm, view_user)


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0088_split_user_editable"),
    ]

    operations = [
        migrations.RunPython(fix_light_admin_permissions, migrations.RunPython.noop),
    ]
