# Generated by Django 3.2 on 2023-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0089_fix_light_admin_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images"
            ),
        ),
    ]
