# Generated by Django 3.2.19 on 2023-06-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0090_increase_image_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[("out", "Outdoors"), ("in", "Indoors")],
                help_text="Will the event be held outdoors?",
                max_length=3,
                null=True,
                verbose_name="Event environment",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="environmental_certificate",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Environmental certificate",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user_consent",
            field=models.BooleanField(
                default=False,
                help_text="I consent to the processing of my personal data?",
                verbose_name="User consent",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="User e-mail"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="User name"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user_organization",
            field=models.CharField(
                blank=True,
                help_text="Event organizer information.",
                max_length=255,
                null=True,
                verbose_name="User organization",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user_phone_number",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="User phone number"
            ),
        ),
    ]
