# Generated by Django 3.2.19 on 2023-06-20 10:45

from django.db import migrations, models


def _set_as_service_language(apps, schema_editor, lang_code):
    Language = apps.get_model("events", "Language")

    try:
        # Set service_language to True
        lang = Language.objects.get(id=lang_code)
        lang.service_language = True
        lang.save()
    except Language.DoesNotExist:
        pass


def set_default_service_languages(apps, schema_editor):
    for lang in ["en", "fi", "sv"]:
        _set_as_service_language(apps, schema_editor, lang)


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0091_add_new_event_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="service_language",
            field=models.BooleanField(
                default=False,
                verbose_name="Can be used as registration service language",
            ),
        ),
        migrations.RunPython(set_default_service_languages, migrations.RunPython.noop),
    ]
