# Generated by Django 3.2.20 on 2023-08-03 09:50

from django.db import migrations, models


def truncate_str(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    qs = Event.objects.filter(provider_contact_info__gt=255)
    langs = ["", "en", "fi", "sv", "ar", "ru", "zh_hans"]
    for event in qs:
        for lang in langs:
            if lang:
                attr = f"provider_contact_info_{lang}"
            else:
                attr = "provider_contact_info"
            if val := getattr(event, attr):
                setattr(event, attr, val[:255])
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0092_language_service_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info_ar",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info_en",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info_fi",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info_ru",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info_sv",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="provider_contact_info_zh_hans",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Provider's contact info",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, truncate_str),
    ]
