# Generated by Django 3.2.20 on 2023-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0093_increase_provider_contact_info_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="user_editable_registrations",
            field=models.BooleanField(
                default=False,
                verbose_name="Owning organization's registrations may be edited by users",
            ),
        ),
    ]
