# Generated by Django 3.2.22 on 2023-10-31 10:11

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0096_alter_event_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFullText",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="full_text_event",
                        serialize=False,
                        to="events.event",
                    ),
                ),
                ("event_last_modified_time", models.DateTimeField()),
                ("place_last_modified_time", models.DateTimeField()),
                (
                    "search_vector_fi",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "search_vector_en",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "search_vector_sv",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
