# Generated by Django 3.2.23 on 2023-12-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0097_eventfulltext"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="user_editable_registration_price_groups",
            field=models.BooleanField(
                default=False,
                verbose_name="Owner organization's registration price groups may be edited by users",
            ),
        ),
    ]
