# Generated by Django 3.2.23 on 2024-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0039_offer_price_group"),
        ("events", "0098_datasource_user_editable_registration_price_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="price_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers",
                through="registrations.OfferPriceGroup",
                to="registrations.PriceGroup",
            ),
        ),
    ]
