# Generated by Django 4.2.20 on 2025-03-21 12:26

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0100_alter_event_maximum_attendee_capacity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="XEventFullText",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="x_full_text",
                        serialize=False,
                        to="events.event",
                    ),
                ),
                ("event_last_modified_time", models.DateTimeField()),
                ("place_last_modified_time", models.DateTimeField()),
                (
                    "words_fi",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "words_en",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "words_sv",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "search_vector_fi",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "search_vector_en",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "search_vector_sv",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="x_full_text_place",
                        to="events.place",
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector_fi"],
                        name="events_xeve_search__99ed8d_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector_en"],
                        name="events_xeve_search__f75e8c_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector_sv"],
                        name="events_xeve_search__35e641_gin",
                    ),
                ],
            },
        ),
    ]
