# Generated by Django 4.2.20 on 2025-05-06 18:35

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0102_alter_eventsearchindex_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsearchindex",
            name="words_en",
        ),
        migrations.RemoveField(
            model_name="eventsearchindex",
            name="words_fi",
        ),
        migrations.RemoveField(
            model_name="eventsearchindex",
            name="words_sv",
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="search_vector_ar",
            field=django.contrib.postgres.search.SearchVectorField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="search_vector_ru",
            field=django.contrib.postgres.search.SearchVectorField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="search_vector_zh_hans",
            field=django.contrib.postgres.search.SearchVectorField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ar_weight_a",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ar_weight_b",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ar_weight_c",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ar_weight_d",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_en_weight_a",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_en_weight_b",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_en_weight_c",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_en_weight_d",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_fi_weight_a",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_fi_weight_b",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_fi_weight_c",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_fi_weight_d",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ru_weight_a",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ru_weight_b",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ru_weight_c",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_ru_weight_d",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_sv_weight_a",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_sv_weight_b",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_sv_weight_c",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_sv_weight_d",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_zh_hans_weight_a",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_zh_hans_weight_b",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_zh_hans_weight_c",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="eventsearchindex",
            name="words_zh_hans_weight_d",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AddIndex(
            model_name="eventsearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_zh_hans"], name="events_even_search__92d93e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="eventsearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_ru"], name="events_even_search__4626e5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="eventsearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_ar"], name="events_even_search__22276d_gin"
            ),
        ),
    ]
