# Generated by Django 4.2.21 on 2025-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0103_eventsearchindex_weighted_words_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsearchindex",
            name="event_last_modified_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventsearchindex",
            name="place_last_modified_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
