# Generated by Django 4.2.23 on 2025-09-12 09:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("events", "0104_alter_eventsearchindex_event_last_modified_time_and_more"),
    ]

    operations = [
        # Events table indexes
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "data_source_id_publication_status_idx" ON "public"."events_event"("data_source_id","publication_status");',
            reverse_sql='DROP INDEX IF EXISTS "data_source_id_publication_status_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "publication_status_idx" ON "public"."events_event"("publication_status");',
            reverse_sql='DROP INDEX IF EXISTS "publication_status_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "event_status_idx" ON "public"."events_event"("event_status");',
            reverse_sql='DROP INDEX IF EXISTS "event_status_idx";',
        ),
        # Events event in language table indexes
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "language_id_event_id_idx" ON "public"."events_event_in_language"("language_id","event_id");',
            reverse_sql='DROP INDEX IF EXISTS "language_id_event_id_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "event_id_language_id_idx" ON "public"."events_event_in_language"("event_id","language_id");',
            reverse_sql='DROP INDEX IF EXISTS "event_id_language_id_idx";',
        ),
        # Organization table indexes
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "tree_id_lft_idx" ON "public"."django_orghierarchy_organization"("tree_id","lft");',
            reverse_sql='DROP INDEX IF EXISTS "tree_id_lft_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "id_tree_id_idx" ON "public"."django_orghierarchy_organization"("id","tree_id");',
            reverse_sql='DROP INDEX IF EXISTS "id_tree_id_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "lft_idx" ON "public"."django_orghierarchy_organization"("lft");',
            reverse_sql='DROP INDEX IF EXISTS "lft_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "tree_id_id_idx" ON "public"."django_orghierarchy_organization"("tree_id","id");',
            reverse_sql='DROP INDEX IF EXISTS "tree_id_id_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "id_replaced_by_id_idx" ON "public"."django_orghierarchy_organization"("id","replaced_by_id");',
            reverse_sql='DROP INDEX IF EXISTS "id_replaced_by_id_idx";',
        ),
        # Keyword and place table indexes
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "data_source_id_n_events_idx" ON "public"."events_keyword"("data_source_id","n_events");',
            reverse_sql='DROP INDEX IF EXISTS "data_source_id_n_events_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "n_events_data_source_id_idx" ON "public"."events_place"("n_events","data_source_id");',
            reverse_sql='DROP INDEX IF EXISTS "n_events_data_source_id_idx";',
        ),
    ]
