# Generated by Django 5.2.5 on 2025-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0104_alter_eventsearchindex_event_last_modified_time_and_more"),
        ("registrations", "0057_alter_registration_price_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="price_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers",
                through="registrations.OfferPriceGroup",
                through_fields=("offer", "price_group"),
                to="registrations.pricegroup",
            ),
        ),
    ]
