# Generated by Django 4.2.23 on 2025-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0104_alter_eventsearchindex_event_last_modified_time_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["data_source_id", "publication_status"],
                name="data_source_publ_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["publication_status"], name="publication_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_status"], name="event_status_idx"),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                fields=["data_source_id", "n_events"],
                name="data_source_id_n_events_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["n_events", "data_source_id"],
                name="n_events_data_source_id_idx",
            ),
        ),
    ]
