# Generated by Django 4.2.23 on 2025-09-15 06:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("events", "0105_add_events_place_keyword_indexes"),
    ]

    operations = [
        # Events event in language table indexes
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "language_id_event_id_idx" ON "public"."events_event_in_language"("language_id","event_id");',
            reverse_sql='DROP INDEX IF EXISTS "language_id_event_id_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY "event_id_language_id_idx" ON "public"."events_event_in_language"("event_id","language_id");',
            reverse_sql='DROP INDEX IF EXISTS "event_id_language_id_idx";',
        ),
    ]
