# Generated by Django 5.2.6 on 2025-09-15 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_orghierarchy", "0012_alter_organization_unique_together_and_more"),
        ("events", "0106_add_events_in_language_indexes"),
        ("munigeo", "0005_update_translation_foreign_keys"),
        ("registrations", "0057_alter_registration_price_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="price_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers",
                through="registrations.OfferPriceGroup",
                through_fields=("offer", "price_group"),
                to="registrations.pricegroup",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["tree_id", "lft"], name="events_event_tree_id_lft_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["tree_id", "lft"], name="events_place_tree_id_lft_idx"
            ),
        ),
    ]
