# Generated by Django 5.2.9 on 2026-01-20 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0107_alter_offer_price_groups_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time when created.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="data_source",
            field=models.ForeignKey(
                help_text="Source of the data.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_%(class)s_data",
                to=settings.DJANGO_ORGHIERARCHY_DATASOURCE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.CharField(
                help_text="Consists of source prefix and source specific identifier.",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Time when last modified.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="origin_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier in the original data source.",
                max_length=100,
                null=True,
                verbose_name="Origin ID",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time when created.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="data_source",
            field=models.ForeignKey(
                help_text="Source of the data.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_%(class)s_data",
                to=settings.DJANGO_ORGHIERARCHY_DATASOURCE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="id",
            field=models.CharField(
                help_text="Consists of source prefix and source specific identifier.",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Time when last modified.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="origin_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier in the original data source.",
                max_length=100,
                null=True,
                verbose_name="Origin ID",
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time when created.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="data_source",
            field=models.ForeignKey(
                help_text="Source of the data.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_%(class)s_data",
                to=settings.DJANGO_ORGHIERARCHY_DATASOURCE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="id",
            field=models.CharField(
                help_text="Consists of source prefix and source specific identifier.",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Time when last modified.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordset",
            name="origin_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier in the original data source.",
                max_length=100,
                null=True,
                verbose_name="Origin ID",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time when created.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="data_source",
            field=models.ForeignKey(
                help_text="Source of the data.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_%(class)s_data",
                to=settings.DJANGO_ORGHIERARCHY_DATASOURCE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.CharField(
                help_text="Consists of source prefix and source specific identifier.",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Time when last modified.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="origin_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier in the original data source.",
                max_length=100,
                null=True,
                verbose_name="Origin ID",
            ),
        ),
    ]
