# Generated by Django 5.2.13 on 2026-04-22 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_orghierarchy", "0013_add_organization_indexes"),
        ("events", "0108_alter_event_created_by_alter_event_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(("deleted", False), ("publication_status", 1)),
                fields=["end_time", "type_id"],
                name="event_common_search_idx",
            ),
        ),
    ]
