# Generated by Django 5.2.15 on 2026-06-12 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_orghierarchy", "0013_add_organization_indexes"),
        ("events", "0109_event_event_common_search_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="keyword",
            name="keywords_index",
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("n_events__gt", 0)),
                fields=["name_fi"],
                name="keywords_index_fi",
            ),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("n_events__gt", 0)),
                fields=["name_sv", "name_fi"],
                name="keywords_index_sv",
            ),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("n_events__gt", 0)),
                fields=["name_en", "name_fi"],
                name="keywords_index_en",
            ),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("n_events__gt", 0)),
                fields=["name_zh_hans", "name_fi"],
                name="keywords_index_zh_hans",
            ),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("n_events__gt", 0)),
                fields=["name_ru", "name_fi"],
                name="keywords_index_ru",
            ),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("n_events__gt", 0)),
                fields=["name_ar", "name_fi"],
                name="keywords_index_ar",
            ),
        ),
    ]
