# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0056_fix_chinese_lang_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension_course', serialize=False, to='events.Event', verbose_name='event')),
                ('enrolment_start_time', models.DateTimeField(blank=True, null=True, verbose_name='enrolment start time')),
                ('enrolment_end_time', models.DateTimeField(blank=True, null=True, verbose_name='enrolment end time')),
                ('maximum_attendee_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum attendee capacity')),
                ('minimum_attendee_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='minimum attendee capacity')),
                ('remaining_attendee_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='remaining attendee capacity')),
            ],
            options={
                'ordering': ('event',),
            },
        ),
    ]
