trigger: none
pr: none
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: linkedevents-pipelines
      type: git
      # Azure DevOps project/repository
      name: linkedevents/linkedevents-pipelines
  pipelines:
    - pipeline: build-linkedevents-api
      source: build-linkedevents-api
      trigger:
        branches:
          include:
            - refs/tags/staging-*

extends:
  template: azure-pipelines-deploy-linkedevents-api-staging.yml@linkedevents-pipelines
  parameters:
    buildenv: staging
