# This is a base build pipeline and it should not be triggered,
# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: false
  branches:
    include:
      - develop
      - master
      - features/*

pr:
 autoCancel: true
 drafts: true
 branches:
   include:
     - develop
     - master

# By default, use self-hosted agents
pool: Default

# Image tag name for Fuse projects
#parameters:
#- name: imagetag
#  displayName: Image tag to be built and/or deployed
#  type: string
#  default: latest

resources:
  repositories:
  # Azure Repos
  - repository: templates
    type: git
    ref: refs/heads/dev
    name: devops-toolchain/pipeline-templates
  # Azure Repos
  - repository: pipelines
    type: git
    name: linkedevents-pipelines


stages:
- template: stage-templates/build-pipeline.yml@templates
  parameters:
    environment: development
    openShiftServiceConnection: linkedevents-dev
    app: linkedevents-api
    project: linkedevents
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/docker/django/Dockerfile'
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(tag)
