# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- template: stage-templates/build-pipeline.yml@templates
  parameters:
    environment: development
    openShiftServiceConnection: linkedevents-dev
    app: linkedevents-api
    project: linkedevents
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/docker/django/Dockerfile'
        tags: |
          $(tag)
