# Production environment deploy pipeline
# Must be triggered manually

trigger: none
pr: none
pool: Production

parameters:
  - name: buildenv
    displayName: Build environment
    type: string
    default: "-prod"
    values:
      - "-prod"

resources:
  repositories:
    - repository: linkedevents-pipelines
      type: git
      name: linkedevents/linkedevents-pipelines

extends:
  template: azure-pipelines-deploy-linkedevents-api-prod.yml@linkedevents-pipelines
  parameters:
    buildenv: ${{ parameters.buildenv }}
