# Test environment deploy pipeline
# Triggers automatically after a build of test branch

trigger: none
pr: none
pool: Default

parameters:
  - name: buildenv
    displayName: Build environment
    type: string
    default: "-dev"
    values:
      - "-dev"
      - "-prod"

resources:
  repositories:
    - repository: linkedevents-pipelines
      type: git
      name: linkedevents/linkedevents-pipelines
#  pipelines:
#    - pipeline: build-linkedevents-api
#      source: build-linkedevents-api
#      trigger:
#        branches:
#          include:
#            - refs/heads/main

extends:
  template: azure-pipelines-deploy-linkedevents-api-test.yml@linkedevents-pipelines
  parameters:
    buildenv: ${{ parameters.buildenv }}
