# Dev environment deploy pipeline
# Triggers automatically after a build of develop branch

trigger: none
pool: Default
pr:
  branches:
    include:
      - develop


parameters:
  - name: buildenv
    displayName: Build environment
    type: string
    default: "-dev"
    values:
      - "-prod"
      - "-staging"
      - "-dev"

# Check out multiple repositories in your pipeline
resources:
  repositories:
    # Azure Repos
    - repository: templates
      type: git
      ref: refs/heads/dev
      name: devops-toolchain/pipeline-templates
    # Azure Repos
    - repository: pipelines
      type: git
      name: linkedevents-pipelines
    - repository: linkedevents-pipelines-ref
      type: git
      name: linkedevents/linkedevents-pipelines


# Variables specified at the pipeline level
variables:
  location: westeurope

# By default, use self-hosted agents
# pool: Default

stages:
  - template: stage-templates/build-pipeline.yml@templates
    parameters:
      environment: development
      openShiftServiceConnection: kerrokantasi-dev
      azServConn: hki-platta-kerrokantasi-devtest
      app: linkedevents-api
      project: linkedevents
      buildenv: -dev
  #- template: pipeline-templates/deploy-pipeline-linkedevents-api.yml@linkedevents-pipelines-ref
  #  parameters:
  #    environment: staging
  #    openShiftServiceConnection: linkedevents-staging
  #    azServConn: hki-platta-linkedevents-staging
  #    additionalFilesForce:
  #      - devops/linkedevents-elasticsearch-config.yml
  #    buildenv: -prod