# Staging environment deploy pipeline
# Must be triggered manually

trigger: none
pr: none
pool: Default

parameters:
  - name: buildenv
    displayName: Build environment
    type: string
    default: "-prod"
    values:
      - "-dev"
      - "-prod"

resources:
  repositories:
    # Azure DevOps repository
    - repository: linkedevents-pipelines
      type: git
      # Azure DevOps project/repository
      name: linkedevents/linkedevents-pipelines
  pipelines:
    - pipeline: build-linkedevents-api
      source: build-linkedevents-api
      trigger:
        branches:
          include:
            - refs/tags/release-*
extends:
  template: azure-pipelines-deploy-linkedevents-api-staging.yml@linkedevents-pipelines
