# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: false
  branches:
    include:
      - develop
      - master
      - features/*

pr:
 autoCancel: true
 drafts: true
 branches:
   include:
     - develop
     - master

resources:
  repositories:
    # Azure DevOps repository
    - repository: linkedevents-pipelines
      type: git
      # Azure DevOps project/repository
      name: linkedevents/linkedevents-pipelines
  pipelines:
    # Pipeline trigger
    - pipeline: build
      source: build-linkedevents-api
      # Run deploy-dev pipeline when any run of build pipeline completes
      trigger: true

variables:
  tag: '$(Build.BuildId)'

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-linkedevents-api-master.yml
  # Drupal example: azure-pipelines-drupal-master.yml
  template: azure-pipelines-deploy-linkedevents-api-dev.yml@linkedevents-pipelines
  # Image tag name for Fuse projects
  #parameters:
  #imagetag: ${{ parameters.imagetag }}