trigger: none
pr: none
pool: Default

parameters:
  - name: buildenv
    displayName: Build environment
    type: string
    default: "-prod"
    values:
      - "-prod"
      - "-dev"


resources:
  repositories:
    # Azure DevOps repository
    - repository: linkedevents-pipelines
      type: git
      # Azure DevOps project/repository
      name: linkedevents/linkedevents-pipelines

extends:
  template: azure-pipelines-deploy-linkedevents-api-staging.yml@linkedevents-pipelines
