# Generated by Django 5.2.9 on 2026-01-27 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit_log", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLogEntry",
        ),
    ]
