# Generated by Django 4.2.15 on 2024-08-21 12:54
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("data_analytics", "0001_initial"),
    ]

    dependencies = []

    operations = []
