# Generated by Django 4.2.11 on 2024-05-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knox", "0008_remove_authtoken_salt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAnalyticsAuthToken",
            fields=[
                (
                    "authtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="knox.authtoken",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            bases=("knox.authtoken",),
        ),
    ]
