import pytest

from events.importer.enkora import EnkoraImporter


class TestEnkoraImporter:
    @pytest.mark.django_db
    @pytest.mark.parametrize(
        "test_input_descriptions,expected_ages",
        [
            ("Äijäjumppa", (None, None)),
            ("Aikuisten tekniikka uimakoulu", (None, None)),
            ("Aikuisten tekniikkauimakoulu", (None, None)),
            ("ALKEET 5-6 -VUOTIAAT", (5, 6)),
            ("ALKEET 5-6-VUOTIAAT", (5, 6)),
            ("ALKEET yli 7 -vuotiaat", (7, None)),
            ("ALKEET YLI 7-vuotiaat", (7, None)),
            ("ALKEET, 5-6 -vuotiaat", (5, 6)),
            ("ALKEET, naiset", (None, None)),
            ("ALKEET, työikäiset", (None, None)),
            ("ALKEET, yli 7 -vuotiaat", (7, None)),
            ("Alkeisjatko uimakoulu, työikäiset", (None, None)),
            ("Alkeisjatko, työikäiset", (None, None)),
            ("Alkeisjatkouimakoulu N, työikäiset", (None, None)),
            ("Alkeisuimakoulu, työikäiset N+M", (None, None)),
            ("AquaPolo -kurssi M + N", (None, None)),
            ("AquaPoLo -kurssi Naiset", (None, None)),
            ("Balans och styrketräning D + H", (None, None)),
            ("Balansgång D + H", (None, None)),
            ("Circuit", (None, None)),
            ("Core ja kehonhuolto", (None, None)),
            ("Dancemix", (None, None)),
            ("Easy Hockey", (None, None)),
            ("EasySport jääkiekko", (None, None)),
            ("EasySport luistelu", (None, None)),
            ("EasySport -luistelukoulu 1. - 3. lk.", (7, 10)),
            ("EasySport -mailapelit 1. - 4. lk.", (7, 11)),
            ("EasySport -mailapelit 1. - 6. lk.", (7, 13)),
            ("EasySport -mailapelit 3. - 6. lk.", (9, 13)),
            ("EasySport -mailapelit 5. - 6. lk.", (11, 13)),
            ("EASYSPORT MELONKURSSI 12-15 -vuotiaat", (12, 15)),
            ("EASYSPORT MELONKURSSI 9-12 -vuotiaat", (9, 12)),
            ("EASYSPORT MELONTA 10-13 -vuotiaat", (10, 13)),
            ("EASYSPORT MELONTA 12-15 -vuotiaat", (12, 15)),
            ("EASYSPORT MELONTA 13-15 -vuotiaat", (13, 15)),
            ("EASYSPORT MELONTA 9-12 -vuotiaat", (9, 12)),
            ("EASYSPORT PADEL-MAILAPELIKURSSI 10-13 -vuotiaat", (10, 13)),
            ("EasySport -Parkour, akrobatia ja sirkuslajit", (None, None)),
            ("EasySport -sirkus", (None, None)),
            ("EasySport -sulkapallo &  squash 3. - 4. lk.", (9, 11)),
            ("EasySport -sulkapallo & squash 5. - 6. lk.", (11, 13)),
            ("EasySport -sulkapallo ja squash 3. - 4. lk.", (9, 11)),
            ("EasySport -sulkapallo ja squash 5. - 6. lk.", (11, 13)),
            ("EasySport -tanssi 1. - 6. lk.", (7, 13)),
            ("EasySport -tanssi 1. - 6. lk. (Break dance)", (7, 13)),
            ("EasySport -tanssi 1. - 6. lk. (Hip Hop, opetuskieli englanti)", (7, 13)),
            ("EasySport -tanssi 1. - 6. lk. (Showtanssi)", (7, 13)),
            ("EasySport Temppu ja tramppa", (None, None)),
            ("EASYSPORT TENNIS, ALKEET 10-12 -vuotiaat", (10, 12)),
            ("EASYSPORT TENNIS, ALKEET yli 10 -vuotiaat", (10, None)),
            ("EASYSPORT TENNIS, ALKEET,  7-9 -vuotiaat", (7, 9)),
            ("EASYSPORT TENNIS, ALKEET, yli 10 -vuotiaat", (10, None)),
            ("EASYSPORT YLEISURHEILUKOULU, 7-14 -vuotiaat", (7, 14)),
            ("ERITYISLASTEN UIMAKOULU ALKEET YLI 6 -VUOTIAAT", (6, None)),
            ("ERITYISLASTEN UIMAKOULU JATKO YLI 6 -VUOTIAAT", (6, None)),
            ("ERITYISLASTEN UIMAKOULU, ALKEET, yli 7 -vuotiaat", (7, None)),
            ("Erityislasten vesiliikunta", (None, None)),
            ("Erityislasten vesiliikunta 10-16 -vuotiaat", (10, 16)),
            ("Erityislasten vesiliikunta 6-9 -vuotiaat", (6, 9)),
            ("Erityislasten vesiseikkailu", (None, None)),
            ("Foam roller", (None, None)),
            ("Foam roller & kehonhuolto", (None, None)),
            ("Fortsättningssimskola på svenska för nybörjare, 5-6 år", (5, 6)),
            ("Hallivesijumppa", (None, None)),
            ("Hyvänolonjumppa", (None, None)),
            ("Hyväolo", (None, None)),
            ("Itsenäinen harjoittelu kuntosalissa ja uima-altaassa N+M", (None, None)),
            ("Itsenäinen kuntosaliharjoittelu /Aktiivix", (None, None)),
            ("Jääkiekko", (None, None)),
            ("JATKO", (None, None)),
            ("JATKO 1", (None, None)),
            ("Jatko 1 (10m uimataito vaaditaan)", (None, None)),
            ("JATKO 1, YLI 6 -VUOTIAAT", (6, None)),
            ("Jatko 1, yli 6 -vuotiaat (10m uimataito vaaditaan)", (6, None)),
            ("JATKO 2", (None, None)),
            ("JATKO 2, YLI 6 -VUOTIAAT", (6, None)),
            ("Jatko 2, yli 6-vuotiaat (25 m uimataito vaaditaan)", (6, None)),
            ("JATKO YLI 6 -VUOTIAAT", (6, None)),
            ("Jatko, työikäiset", (None, None)),
            ("JATKOUIMAKOULU, Työikäiset", (None, None)),
            ("Jumppakortti Seniorit kevät 2018", (None, None)),
            ("Jumppakortti Seniorit Kevät 2019", (None, None)),
            ("Jumppakortti Seniorit kevät 7.1. - 27.4.2020", (None, None)),
            ("Jumppakortti Työikäiset kevät 2018", (None, None)),
            ("Jumppakortti Työikäiset Kevät 2019", (None, None)),
            ("Jumppakortti Työikäiset kevät 7.1. - 27.4.2020", (None, None)),
            ("Juoksukoulu", (None, None)),
            ("Kahvakuula", (None, None)),
            ("Kahvakuula M + N", (None, None)),
            ("Kehitysvammaisten liikuntaryhmä M + N", (None, None)),
            ("Kehonhuolto", (None, None)),
            ("Kehonhuolto M + N", (None, None)),
            ("KESÄJUMPPA", (None, None)),
            ("Kesäkuntokurssi, kuulonäkövammaiset", (None, None)),
            ("Kesäkuntokurssi, mielenterveyskuntoutujat ja", (None, None)),
            ("KEVYT KESÄJUMPPA", (None, None)),
            ("Kevytjumppa", (None, None)),
            ("Kevytjumppa M + N", (None, None)),
            ("Kevytjumppa N+M", (None, None)),
            ("Kevytjumppa,  Kuulovammaiset ja huonokuuloise", (None, None)),
            ("Kevytjumppa,  Kuulovammaiset ja huonokuuloiset  M + N", (None, None)),
            ("Kiekkokoulu", (None, None)),
            ("Kierto- ja kuntosaliharjoittelu, Kuulovammais", (None, None)),
            (
                "Kierto- ja kuntosaliharjoittelu, Kuulovammaiset ja huonokuuloiset M + N",
                (None, None),
            ),
            ("Kiinteytys", (None, None)),
            ("Konditionssal, Instruerad D + H", (None, None)),
            ("Koululaisuinti", (None, None)),
            ("Kroppsvård och stretching", (None, None)),
            ("Kuntojumppa", (None, None)),
            ("Kuntokävely", (None, None)),
            ("Kuntosalin starttikurssi M + N", (None, None)),
            ("Kuntosaliohjelman laadinta", (None, None)),
            ("Kuntosaliohjelmat ja testaus", (None, None)),
            ("Kuntosalistartti", (None, None)),
            ("Kuulovammaisten lasten Alkeet 4-5-vuotiaat", (4, 5)),
            ("Kuulovammaisten lasten Alkeet 4-7-vuotiaat", (4, 7)),
            ("Kuulovammaisten lasten Alkeet 5-6-vuotiaat", (5, 6)),
            ("Kuulovammaisten lasten Alkeet 6-8-vuotiaat", (6, 8)),
            ("Kuulovammaisten lasten Alkeet yli 7-vuotiaat", (7, None)),
            ("Kuulovammaisten lasten jatko 1, yli 6 -vuotiaat", (6, None)),
            ("Lapsi-aikuinen temppujumppa 2-3 -vuotiaat", (2, 3)),
            ("Lapsi-aikuinen temppujumppa 3-4 -vuotiaat", (3, 4)),
            ("Lattarijumppa", (None, None)),
            ("Lempeää jooga aloittelijoille", (None, None)),
            ("Liikuntahulinat", (None, None)),
            ("Liikuntakaruselli", (None, None)),
            ("LIVcircuit", (None, None)),
            ("LIVcore M + N", (None, None)),
            ("LIVhyväolo", (None, None)),
            ("LIVkahvakuula", (None, None)),
            ("LIVkahvakuula M + N", (None, None)),
            ("LIVkevytjumppa", (None, None)),
            ("LIVkevytjumppa M + N", (None, None)),
            ("LIVlattarit", (None, None)),
            ("LIVsyke", (None, None)),
            ("LIVSyke M + N", (None, None)),
            ("LIVteema", (None, None)),
            ("LIVULKOTREENI", (None, None)),
            ("LIVvenyttely", (None, None)),
            ("LIVvenyttely M + N", (None, None)),
            ("LIVvoima", (None, None)),
            ("LIVvoima M + N", (None, None)),
            ("Luistelukoulu 1. - 3. lk.", (7, 10)),
            ("Luistelukoulu 4-6 lk.", (10, 13)),
            ("Luovan liikkeen ryhmä, kehitysvammaiset aikuiset", (None, None)),
            ("Luovan liikkeen ryhmä, Mielenterveyskuntoutu", (None, None)),
            ("Mailapelit 1. - 6. lk.", (7, 13)),
            ("Mailapelit 3. - 6. lk.", (9, 13)),
            ("Mammatreeni", (None, None)),
            ("Maratonjumppa", (None, None)),
            ("Metsäjooga", (None, None)),
            ("Niska-selkähuolto", (None, None)),
            ("Niska-selkätunti", (None, None)),
            ("NYBÖRJARSIM FÖR ÖVER 7 ÅR", (7, None)),
            ("NYBÖRJARSIM PÅ SVENSKA FÖR BARN, 6-9 år", (6, 9)),
            ("NYBÖRJARSIM PÅ SVENSKA FÖR FLICKOR OCH POJKAR, 5-6 år", (5, 6)),
            ("Ohjattu kuntosaliCircuit M + N", (None, None)),
            ("Ohjattu kuntosaliharjoittelu + 75 vuotiaat M + N", (75, None)),
            ("Ohjattu kuntosaliharjoittelu M", (None, None)),
            ("Ohjattu kuntosaliharjoittelu M + N", (None, None)),
            ("Ohjattu kuntosaliharjoittelu M+N", (None, None)),
            ("Ohjattu kuntosaliharjoittelu Miehet", (None, None)),
            ("Ohjattu kuntosaliharjoittelu Naiset", (None, None)),
            ("Ohjattu Kuntosaliharjoittelu, Kehitysvammaise", (None, None)),
            ("Ohjattu Kuntosaliharjoittelu, Kehitysvammaiset M + N", (None, None)),
            ("Ohjattu Kuntosaliharjoittelu, Kehitysvammaiset M+N", (None, None)),
            ("Ohjattu kuntosaliharjoittelu, Mielenterveysku", (None, None)),
            (
                "Ohjattu kuntosaliharjoittelu, Mielenterveyskuntoutujat M + N",
                (None, None),
            ),
            ("Päiväkotiuinti, Mustikka", (None, None)),
            ("Pallomylly", (None, None)),
            ("Parkour", (None, None)),
            ("Parkour, akrobatia ja sirkuslajit", (None, None)),
            ("Perhehulinat", (None, None)),
            ("Perheliikunta 2-3 -vuotiaat", (2, 3)),
            ("Perhepalloilu", (None, None)),
            ("Pilates", (None, None)),
            ("Porrastreeni", (None, None)),
            ("PUISTOJUMPPA", (None, None)),
            ("PUISTOJUMPPA (Heteniitynkenttä)", (None, None)),
            ("PUISTOJUMPPA (Kansallismuseo)", (None, None)),
            ("PUISTOJUMPPA (Mellunmäen virkistysalue)", (None, None)),
            ("Puistojumppa ja kävely", (None, None)),
            ("Puistojumppa ja sauvakävely", (None, None)),
            ("Redi", (None, None)),
            ("Säestetty jumppa (kevyt) M + N", (None, None)),
            ("Säestetty jumppa M + N", (None, None)),
            ("Sauvakävely", (None, None)),
            ("SENIORI VESIJUMPPA, MIEHET JA NAISET", (None, None)),
            ("SENIORI VESIJUMPPA, NAISET", (None, None)),
            ("SenioriCircuit", (None, None)),
            ("SenioriCircuit M + N", (None, None)),
            ("SenioriCircuit N+M", (None, None)),
            ("SenioriCore", (None, None)),
            ("SenioriCore N+M", (None, None)),
            ("SenioriCore Naiset", (None, None)),
            ("SenioriCore+Venyttely", (None, None)),
            ("SenioriJumppa Miehet", (None, None)),
            ("SenioriJumppa Naiset", (None, None)),
            ("SenioriKahvakuula", (None, None)),
            ("SenioriKehonhuolto", (None, None)),
            ("SenioriKeppijumppa", (None, None)),
            ("SenioriKevytjumppa N + M", (None, None)),
            ("SenioriKuntojumppa", (None, None)),
            ("SenioriKuntojumppa Naiset", (None, None)),
            ("SenioriKuntokävely", (None, None)),
            ("SenioriKuntokävelyTreeni", (None, None)),
            ("Seniorikuntosalistartti", (None, None)),
            ("SenioriKuntotanssi", (None, None)),
            ("SenioriKuntotanssi Naiset", (None, None)),
            ("SenioriLattarijumppa", (None, None)),
            ("Seniorilattarijumppa Naiset", (None, None)),
            ("SenioriLattarijumppa, Naiset", (None, None)),
            ("SenioriLattarit", (None, None)),
            ("SenioriLattarit Naiset", (None, None)),
            ("Senioriltanssi vasta-alkajille M + N", (None, None)),
            ("SenioriPorrastreeni", (None, None)),
            ("SenioriSäestys", (None, None)),
            ("SenioriSäestys N + M", (None, None)),
            ("SenioriSäestys N+M", (None, None)),
            ("Seniorisäpinät", (None, None)),
            ("SenioriSauvakävely", (None, None)),
            ("SenioriSyke", (None, None)),
            ("SenioriSyke M + N", (None, None)),
            ("SenioriTanssi M + N", (None, None)),
            ("Senioritanssi vasta-alkajille M + N", (None, None)),
            ("SenioriTanssillinenSyke", (None, None)),
            ("SenioriTeema", (None, None)),
            ("SenioriUlkojumppa", (None, None)),
            ("SenioriUlkoliikunta", (None, None)),
            ("SenioriUlkotreeni", (None, None)),
            ("SenioriUlkovoima", (None, None)),
            ("SenioriuUlkojumppa", (None, None)),
            ("SenioriuUlkoliikunta", (None, None)),
            ("SenioriVenytely", (None, None)),
            ("SenioriVenyttely", (None, None)),
            ("SenioriVenyttely M + N", (None, None)),
            ("SenioriVenyttely N + M", (None, None)),
            ("SenioriVKehonhuolto", (None, None)),
            ("SenioriVoima", (None, None)),
            ("SenioriVoima N+M", (None, None)),
            ("Showjazz", (None, None)),
            ("Stolgymnastik", (None, None)),
            ("Stretching", (None, None)),
            ("Sunnuntaijumppa", (None, None)),
            ("Syke", (None, None)),
            ("Syke (tanssillinen)", (None, None)),
            ("Syke/Core", (None, None)),
            ("SYVÄNVEDEN JUMPPA", (None, None)),
            ("Syvänveden jumppa M +N", (None, None)),
            ("Syvänveden jumppa Naiset", (None, None)),
            ("Syvänvedenvesijumppa  M + N", (None, None)),
            ("Tanssillinen syke", (None, None)),
            ("Tasapaino ja core", (None, None)),
            ("Tasapaino- ja voimaharjoittelu", (None, None)),
            ("Tasapaino- ja voimaharjoittelu M + N", (None, None)),
            ("Teema", (None, None)),
            ("Teema M + N", (None, None)),
            ("TEKNIIKKA", (None, None)),
            ("TEKNIIKKA 1, työikäiset", (None, None)),
            ("TEKNIIKKA 1, yli 7 -VUOTIAAT", (7, None)),
            ("TEKNIIKKA, Työikäiset", (None, None)),
            ("Temppuhulinat 2-6 -vuotiaat", (2, 6)),
            ("Temppujumppa 3-4 -vuotiaat", (3, 4)),
            ("Temppujumppa 4-5 vuotiaat", (4, 5)),
            ("Temppujumppa 4-5 -vuotiaat", (4, 5)),
            ("Temppujumppa 5-6 vuotiaat", (5, 6)),
            ("Temppujumppa 5-6 -vuotiaat", (5, 6)),
            ("Temppujumppa 7-9 -vuotiaat", (7, 9)),
            ("Temppujumppa perheet 2-6 -vuotiaat", (2, 6)),
            ("Tempputaito 5-6 -vuotiaat", (5, 6)),
            ("TemppuTaito 7-8 -vuotiaat", (7, 8)),
            ("testikurssi", (None, None)),
            ("TUOLIJUMPPA", (None, None)),
            ("Tuolijumppa M + N", (None, None)),
            ("Tuolijumppa N+M", (None, None)),
            ("Tuolijumppa Naiset", (None, None)),
            ("TYTTÖJEN UIMAKOULU, ALKEET 10 - 12 -VUOTIAAT", (10, 12)),
            ("TYTTÖJEN UIMAKOULU, ALKEET 10 - 16 -VUOTIAAT", (10, 16)),
            ("TYTTÖJEN UIMAKOULU, ALKEET 10-16 -vuotiaat", (10, 16)),
            ("TYTTÖJEN UIMAKOULU, ALKEET 7-9 -vuotiaat", (7, 9)),
            ("TYTTÖJEN UIMAKOULU, ALKEET yli 6 -vuotiaat", (6, None)),
            ("TYTTÖJEN UIMAKOULU, JATKO", (None, None)),
            ("TYTTÖJEN UIMAKOULU, JATKO 1", (None, None)),
            ("TYTTÖJEN UIMAKOULU, JATKO 1 yli 6 -vuotiaat", (6, None)),
            (
                "TYTTÖJEN UIMAKOULU, JATKO 1 yli 6 -vuotiaat (10m uimataito vaaditaan)",
                (6, None),
            ),
            ("TYTTÖJEN UIMAKOULU, TEKNIIKKA yli 6 -vuotiaat", (6, None)),
            ("UINTITEKNIIKKA", (None, None)),
            ("Ulkokuntosalistartti", (None, None)),
            ("Ulkoliikunta Mielenterveyskuntoutujat", (None, None)),
            ("Ulkoliikunta, Länsi", (None, None)),
            ("UlkoTreeni", (None, None)),
            ("UlkoVoima", (None, None)),
            ("Uteträning för seniorer", (None, None)),
            ("Vattengymnastik D + H", (None, None)),
            ("Vattengymnastik, D", (None, None)),
            ("Vattengymnastik, Damer", (None, None)),
            ("Vattengymnastik, Krigsveteraner D +  H", (None, None)),
            ("Venyttely", (None, None)),
            ("Venyttely ja rentoutus", (None, None)),
            ("Venyttely ja rentoutus, Mielenterveyskuntoutu", (None, None)),
            ("Venyttely ja rentoutus, Mielenterveyskuntoutujat M + N", (None, None)),
            ("Venyttely M + N", (None, None)),
            ("Vesijumppa", (None, None)),
            ("Vesijumppa  M + N", (None, None)),
            ("Vesijumppa +75 ja veteraanit", (75, None)),
            ("Vesijumppa +75 ja veteraanit, M+N", (75, None)),
            ("VESIJUMPPA +75 -vuotiaat, NAISET", (75, None)),
            ("Vesijumppa M + N", (None, None)),
            ("Vesijumppa M + N, AVH", (None, None)),
            ("Vesijumppa M+N", (None, None)),
            ("Vesijumppa Miehet", (None, None)),
            ("Vesijumppa N", (None, None)),
            ("Vesijumppa N+M", (None, None)),
            ("Vesijumppa Naiset", (None, None)),
            ("Vesijumppa Naiset 75+", (75, None)),
            ("Vesijumppa syöpään sairastuneille M + N", (None, None)),
            ("Vesijumppa,  M + N", (None, None)),
            ("Vesijumppa, Aivohalvaantuneet M + N", (None, None)),
            ("Vesijumppa, Kehitysvammaiset M + N", (None, None)),
            ("Vesijumppa, Kuulovammaiset ja huonokuuloiset ", (None, None)),
            ("Vesijumppa, M + N", (None, None)),
            ("Vesijumppa, Miehet", (None, None)),
            ("VESIJUMPPA, MIEHET JA NAISET", (None, None)),
            ("Vesijumppa, Mielenterveyskuntoutujat M", (None, None)),
            ("Vesijumppa, Mielenterveyskuntoutujat M + N", (None, None)),
            ("Vesijumppa, Mielenterveyskuntoutujat Naiset", (None, None)),
            ("VESIJUMPPA, N+M", (None, None)),
            ("VESIJUMPPA, NAISET", (None, None)),
            ("Vesijumppa, Neurologiset asiakkaat M + N", (None, None)),
            ("Vesijumppa, syöpään sairastuneille, M + N", (None, None)),
            ("Vesijumppa, veteraani M + N", (None, None)),
            ("Vesijuoksu", (None, None)),
            ("Vesitreeni", (None, None)),
            ("Voima", (None, None)),
            ("Voima M + N", (None, None)),
            ("Voimajumppa", (None, None)),
            ("XXL -vesijumppa -ryhmä M + N", (None, None)),
            ("XXL -vesijumppa -ryhmä Naiset", (None, None)),
            ("XXL_kuntosaliharjoittelu M+N", (None, None)),
            ("XXL-jumppa", (None, None)),
            ("XXL-jumppa M + N", (None, None)),
            ("XXL-kuntosaliharjoittelu N+M", (None, None)),
            ("XXL-startti", (None, None)),
            ("XXL-stratti", (None, None)),
            ("XXL-vesijumppa M + N", (None, None)),
            ("XXL-vesijumppa Naiset", (None, None)),
        ],
    )
    def test_parse_age_range_returns_correct_result(
        self, test_input_descriptions, expected_ages
    ):
        assert (
            EnkoraImporter._parse_description_age(test_input_descriptions)
            == expected_ages
        )

    @pytest.mark.django_db
    @pytest.mark.parametrize(
        "test_input_descriptions,expected_keywords",
        [
            ("Äijäjumppa", {EnkoraImporter.AUDIENCE_MEN, EnkoraImporter.SPORT_JUMPPA}),
            (
                "Aikuisten tekniikka uimakoulu",
                {EnkoraImporter.AUDIENCE_ADULTS, EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "Aikuisten tekniikkauimakoulu",
                {EnkoraImporter.AUDIENCE_ADULTS, EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            ("ALKEET 5-6 -VUOTIAAT", set()),
            ("ALKEET 5-6-VUOTIAAT", set()),
            ("ALKEET yli 7 -vuotiaat", set()),
            ("ALKEET YLI 7-vuotiaat", set()),
            ("ALKEET, 5-6 -vuotiaat", set()),
            ("ALKEET, naiset", {EnkoraImporter.AUDIENCE_WOMEN}),
            ("ALKEET, työikäiset", {EnkoraImporter.AUDIENCE_WORKING_AGE}),
            ("ALKEET, yli 7 -vuotiaat", set()),
            (
                "Alkeisjatko uimakoulu, työikäiset",
                {EnkoraImporter.SPORT_SWIM_SCHOOL, EnkoraImporter.AUDIENCE_WORKING_AGE},
            ),
            ("Alkeisjatko, työikäiset", {EnkoraImporter.AUDIENCE_WORKING_AGE}),
            (
                "Alkeisjatkouimakoulu N, työikäiset",
                {
                    EnkoraImporter.SPORT_SWIM_SCHOOL,
                    EnkoraImporter.AUDIENCE_WOMEN,
                    EnkoraImporter.AUDIENCE_WORKING_AGE,
                },
            ),
            (
                "Alkeisuimakoulu, työikäiset N+M",
                {
                    EnkoraImporter.SPORT_SWIM_SCHOOL,
                    EnkoraImporter.AUDIENCE_WORKING_AGE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                    EnkoraImporter.AUDIENCE_MEN,
                },
            ),
            (
                "AquaPolo -kurssi M + N",
                {
                    EnkoraImporter.SPORT_SWIM_SCHOOL,
                    EnkoraImporter.AUDIENCE_WOMEN,
                    EnkoraImporter.AUDIENCE_MEN,
                },
            ),
            (
                "AquaPoLo -kurssi Naiset",
                {EnkoraImporter.SPORT_SWIM_SCHOOL, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "Balans och styrketräning D + H",
                {
                    EnkoraImporter.AUDIENCE_WOMEN,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                },
            ),
            (
                "Balansgång D + H",
                {
                    EnkoraImporter.AUDIENCE_WOMEN,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                },
            ),
            ("Circuit", {EnkoraImporter.SPORT_GYM}),
            ("Core ja kehonhuolto", {EnkoraImporter.SPORT_GYM}),
            ("Dancemix", {EnkoraImporter.SPORT_DANCE}),
            ("Easy Hockey", {EnkoraImporter.SPORT_ICE_HOCKEY}),
            ("EasySport jääkiekko", {EnkoraImporter.SPORT_ICE_HOCKEY}),
            ("EasySport luistelu", {EnkoraImporter.SPORT_SKATING}),
            ("EasySport -luistelukoulu 1. - 3. lk.", {EnkoraImporter.SPORT_SKATING}),
            ("EasySport -mailapelit 1. - 4. lk.", {EnkoraImporter.SPORT_MAILAPELIT}),
            ("EasySport -mailapelit 1. - 6. lk.", {EnkoraImporter.SPORT_MAILAPELIT}),
            ("EasySport -mailapelit 3. - 6. lk.", {EnkoraImporter.SPORT_MAILAPELIT}),
            ("EasySport -mailapelit 5. - 6. lk.", {EnkoraImporter.SPORT_MAILAPELIT}),
            ("EASYSPORT MELONKURSSI 12-15 -vuotiaat", {EnkoraImporter.SPORT_CANOEING}),
            ("EASYSPORT MELONKURSSI 9-12 -vuotiaat", {EnkoraImporter.SPORT_CANOEING}),
            ("EASYSPORT MELONTA 10-13 -vuotiaat", {EnkoraImporter.SPORT_CANOEING}),
            ("EASYSPORT MELONTA 12-15 -vuotiaat", {EnkoraImporter.SPORT_CANOEING}),
            ("EASYSPORT MELONTA 13-15 -vuotiaat", {EnkoraImporter.SPORT_CANOEING}),
            ("EASYSPORT MELONTA 9-12 -vuotiaat", {EnkoraImporter.SPORT_CANOEING}),
            (
                "EASYSPORT PADEL-MAILAPELIKURSSI 10-13 -vuotiaat",
                {EnkoraImporter.SPORT_PADEL},
            ),
            (
                "EasySport -Parkour, akrobatia ja sirkuslajit",
                {
                    EnkoraImporter.SPORT_PARKOUR,
                    EnkoraImporter.SPORT_ACROBATICS,
                    EnkoraImporter.SPORT_CIRCUS,
                },
            ),
            ("EasySport -sirkus", {EnkoraImporter.SPORT_CIRCUS}),
            (
                "EasySport -sulkapallo &  squash 3. - 4. lk.",
                {EnkoraImporter.SPORT_BADMINTON, EnkoraImporter.SPORT_SQUASH},
            ),
            (
                "EasySport -sulkapallo & squash 5. - 6. lk.",
                {EnkoraImporter.SPORT_BADMINTON, EnkoraImporter.SPORT_SQUASH},
            ),
            (
                "EasySport -sulkapallo ja squash 3. - 4. lk.",
                {EnkoraImporter.SPORT_BADMINTON, EnkoraImporter.SPORT_SQUASH},
            ),
            (
                "EasySport -sulkapallo ja squash 5. - 6. lk.",
                {EnkoraImporter.SPORT_BADMINTON, EnkoraImporter.SPORT_SQUASH},
            ),
            ("EasySport -tanssi 1. - 6. lk.", {EnkoraImporter.SPORT_DANCE}),
            (
                "EasySport -tanssi 1. - 6. lk. (Break dance)",
                {EnkoraImporter.SPORT_DANCE},
            ),
            (
                "EasySport -tanssi 1. - 6. lk. (Hip Hop, opetuskieli englanti)",
                {EnkoraImporter.SPORT_DANCE, EnkoraImporter.LANGUAGE_ENGLISH},
            ),
            (
                "EasySport -tanssi 1. - 6. lk. (Showtanssi)",
                {EnkoraImporter.SPORT_DANCE},
            ),
            ("EasySport Temppu ja tramppa", {EnkoraImporter.SPORT_TRAMPOLINING}),
            ("EASYSPORT TENNIS, ALKEET 10-12 -vuotiaat", {EnkoraImporter.SPORT_TENNIS}),
            (
                "EASYSPORT TENNIS, ALKEET yli 10 -vuotiaat",
                {EnkoraImporter.SPORT_TENNIS},
            ),
            ("EASYSPORT TENNIS, ALKEET,  7-9 -vuotiaat", {EnkoraImporter.SPORT_TENNIS}),
            (
                "EASYSPORT TENNIS, ALKEET, yli 10 -vuotiaat",
                {EnkoraImporter.SPORT_TENNIS},
            ),
            (
                "EASYSPORT YLEISURHEILUKOULU, 7-14 -vuotiaat",
                {EnkoraImporter.SPORT_TRACK_N_FIELD},
            ),
            (
                "ERITYISLASTEN UIMAKOULU ALKEET YLI 6 -VUOTIAAT",
                {EnkoraImporter.SPORT_SWIM_SCHOOL, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            (
                "ERITYISLASTEN UIMAKOULU JATKO YLI 6 -VUOTIAAT",
                {EnkoraImporter.SPORT_SWIM_SCHOOL, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            (
                "ERITYISLASTEN UIMAKOULU, ALKEET, yli 7 -vuotiaat",
                {EnkoraImporter.SPORT_SWIM_SCHOOL, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            (
                "Erityislasten vesiliikunta",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            (
                "Erityislasten vesiliikunta 10-16 -vuotiaat",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            (
                "Erityislasten vesiliikunta 6-9 -vuotiaat",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            (
                "Erityislasten vesiseikkailu",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.SPORT_ADAPTED_PE},
            ),
            ("Foam roller", {EnkoraImporter.SPORT_GYM}),
            ("Foam roller & kehonhuolto", {EnkoraImporter.SPORT_GYM}),
            (
                "Fortsättningssimskola på svenska för nybörjare, 5-6 år",
                {EnkoraImporter.LANGUAGE_SWEDISH},
            ),
            ("Hallivesijumppa", {EnkoraImporter.SPORT_WATER_EXERCISE}),
            ("Hyvänolonjumppa", {EnkoraImporter.SPORT_JUMPPA}),
            ("Hyväolo", {EnkoraImporter.SPORT_RELAXATION}),
            (
                "Itsenäinen harjoittelu kuntosalissa ja uima-altaassa N+M",
                {EnkoraImporter.AUDIENCE_WOMEN, EnkoraImporter.AUDIENCE_MEN},
            ),
            ("Itsenäinen kuntosaliharjoittelu /Aktiivix", {EnkoraImporter.SPORT_GYM}),
            ("Jääkiekko", {EnkoraImporter.SPORT_ICE_HOCKEY}),
            ("JATKO", set()),
            ("JATKO 1", set()),
            ("Jatko 1 (10m uimataito vaaditaan)", set()),
            ("JATKO 1, YLI 6 -VUOTIAAT", set()),
            ("Jatko 1, yli 6 -vuotiaat (10m uimataito vaaditaan)", set()),
            ("JATKO 2", set()),
            ("JATKO 2, YLI 6 -VUOTIAAT", set()),
            ("Jatko 2, yli 6-vuotiaat (25 m uimataito vaaditaan)", set()),
            ("JATKO YLI 6 -VUOTIAAT", set()),
            ("Jatko, työikäiset", {EnkoraImporter.AUDIENCE_WORKING_AGE}),
            (
                "JATKOUIMAKOULU, Työikäiset",
                {EnkoraImporter.SPORT_SWIM_SCHOOL, EnkoraImporter.AUDIENCE_WORKING_AGE},
            ),
            (
                "Jumppakortti Seniorit kevät 2018",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_SENIORS},
            ),
            (
                "Jumppakortti Seniorit Kevät 2019",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_SENIORS},
            ),
            (
                "Jumppakortti Seniorit kevät 7.1. - 27.4.2020",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_SENIORS},
            ),
            (
                "Jumppakortti Työikäiset kevät 2018",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_WORKING_AGE},
            ),
            (
                "Jumppakortti Työikäiset Kevät 2019",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_WORKING_AGE},
            ),
            (
                "Jumppakortti Työikäiset kevät 7.1. - 27.4.2020",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_WORKING_AGE},
            ),
            ("Juoksukoulu", {EnkoraImporter.SPORT_RUNNING}),
            ("Kahvakuula", {EnkoraImporter.SPORT_KETTLEBELL}),
            (
                "Kahvakuula M + N",
                {
                    EnkoraImporter.SPORT_KETTLEBELL,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Kehitysvammaisten liikuntaryhmä M + N",
                {
                    EnkoraImporter.AUDIENCE_INTELLECTUAL_DISABILITY,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Kehonhuolto", {EnkoraImporter.SPORT_GYM}),
            (
                "Kehonhuolto M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("KESÄJUMPPA", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "Kesäkuntokurssi, kuulonäkövammaiset",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kesäkuntokurssi, mielenterveyskuntoutujat ja",
                {EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB},
            ),
            ("KEVYT KESÄJUMPPA", {EnkoraImporter.SPORT_JUMPPA}),
            ("Kevytjumppa", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "Kevytjumppa M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Kevytjumppa N+M",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Kevytjumppa,  Kuulovammaiset ja huonokuuloise",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kevytjumppa,  Kuulovammaiset ja huonokuuloiset  M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_HEARING_IMPAIRED,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Kiekkokoulu", {EnkoraImporter.SPORT_ICE_HOCKEY}),
            (
                "Kierto- ja kuntosaliharjoittelu, Kuulovammais",
                {EnkoraImporter.SPORT_GYM, EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kierto- ja kuntosaliharjoittelu, Kuulovammaiset ja huonokuuloiset M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_HEARING_IMPAIRED,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Kiinteytys", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "Konditionssal, Instruerad D + H",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Koululaisuinti", {EnkoraImporter.SPORT_SWIM_SCHOOL}),
            (
                "Kroppsvård och stretching",
                {
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.SPORT_STRETCHING,
                },
            ),
            ("Kuntojumppa", {EnkoraImporter.SPORT_JUMPPA}),
            ("Kuntokävely", {EnkoraImporter.SPORT_WALKING}),
            (
                "Kuntosalin starttikurssi M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Kuntosaliohjelman laadinta", {EnkoraImporter.SPORT_GYM}),
            ("Kuntosaliohjelmat ja testaus", {EnkoraImporter.SPORT_GYM}),
            ("Kuntosalistartti", {EnkoraImporter.SPORT_GYM}),
            (
                "Kuulovammaisten lasten Alkeet 4-5-vuotiaat",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kuulovammaisten lasten Alkeet 4-7-vuotiaat",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kuulovammaisten lasten Alkeet 5-6-vuotiaat",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kuulovammaisten lasten Alkeet 6-8-vuotiaat",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kuulovammaisten lasten Alkeet yli 7-vuotiaat",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Kuulovammaisten lasten jatko 1, yli 6 -vuotiaat",
                {EnkoraImporter.AUDIENCE_HEARING_IMPAIRED},
            ),
            (
                "Lapsi-aikuinen temppujumppa 2-3 -vuotiaat",
                {EnkoraImporter.SPORT_JUMPPA},
            ),
            (
                "Lapsi-aikuinen temppujumppa 3-4 -vuotiaat",
                {EnkoraImporter.SPORT_JUMPPA},
            ),
            ("Lattarijumppa", {EnkoraImporter.SPORT_DANCE}),
            ("Lempeää jooga aloittelijoille", {EnkoraImporter.SPORT_YOGA}),
            ("Liikuntahulinat", set()),
            ("Liikuntakaruselli", {EnkoraImporter.SPORT_GYM}),
            ("LIVcircuit", {EnkoraImporter.SPORT_GYM}),
            (
                "LIVcore M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("LIVhyväolo", {EnkoraImporter.SPORT_JUMPPA}),
            ("LIVkahvakuula", {EnkoraImporter.SPORT_KETTLEBELL}),
            (
                "LIVkahvakuula M + N",
                {
                    EnkoraImporter.SPORT_KETTLEBELL,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("LIVkevytjumppa", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "LIVkevytjumppa M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("LIVlattarit", {EnkoraImporter.SPORT_DANCE}),
            ("LIVsyke", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "LIVSyke M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("LIVteema", set()),
            ("LIVULKOTREENI", {EnkoraImporter.SPORT_OUTDOOR_PE}),
            ("LIVvenyttely", {EnkoraImporter.SPORT_STRETCHING}),
            (
                "LIVvenyttely M + N",
                {
                    EnkoraImporter.SPORT_STRETCHING,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("LIVvoima", {EnkoraImporter.SPORT_GYM}),
            (
                "LIVvoima M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Luistelukoulu 1. - 3. lk.", {EnkoraImporter.SPORT_SKATING}),
            ("Luistelukoulu 4-6 lk.", {EnkoraImporter.SPORT_SKATING}),
            (
                "Luovan liikkeen ryhmä, kehitysvammaiset aikuiset",
                {EnkoraImporter.AUDIENCE_INTELLECTUAL_DISABILITY},
            ),
            (
                "Luovan liikkeen ryhmä, Mielenterveyskuntoutu",
                {EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB},
            ),
            ("Mailapelit 1. - 6. lk.", {EnkoraImporter.SPORT_MAILAPELIT}),
            ("Mailapelit 3. - 6. lk.", {EnkoraImporter.SPORT_MAILAPELIT}),
            (
                "Mammatreeni",
                {EnkoraImporter.AUDIENCE_WOMEN, EnkoraImporter.SPORT_JUMPPA},
            ),
            ("Maratonjumppa", {EnkoraImporter.SPORT_JUMPPA}),
            ("Metsäjooga", {EnkoraImporter.SPORT_YOGA}),
            ("Niska-selkähuolto", {EnkoraImporter.SPORT_JUMPPA}),
            ("Niska-selkätunti", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "NYBÖRJARSIM FÖR ÖVER 7 ÅR",
                {EnkoraImporter.LANGUAGE_SWEDISH, EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "NYBÖRJARSIM PÅ SVENSKA FÖR BARN, 6-9 år",
                {EnkoraImporter.LANGUAGE_SWEDISH, EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "NYBÖRJARSIM PÅ SVENSKA FÖR FLICKOR OCH POJKAR, 5-6 år",
                {EnkoraImporter.LANGUAGE_SWEDISH, EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "Ohjattu kuntosaliCircuit M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Ohjattu kuntosaliharjoittelu + 75 vuotiaat M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Ohjattu kuntosaliharjoittelu M",
                {EnkoraImporter.SPORT_GYM, EnkoraImporter.AUDIENCE_MEN},
            ),
            (
                "Ohjattu kuntosaliharjoittelu M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Ohjattu kuntosaliharjoittelu M+N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Ohjattu kuntosaliharjoittelu Miehet",
                {EnkoraImporter.SPORT_GYM, EnkoraImporter.AUDIENCE_MEN},
            ),
            (
                "Ohjattu kuntosaliharjoittelu Naiset",
                {EnkoraImporter.SPORT_GYM, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "Ohjattu Kuntosaliharjoittelu, Kehitysvammaise",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_INTELLECTUAL_DISABILITY,
                },
            ),
            (
                "Ohjattu Kuntosaliharjoittelu, Kehitysvammaiset M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_INTELLECTUAL_DISABILITY,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Ohjattu Kuntosaliharjoittelu, Kehitysvammaiset M+N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_INTELLECTUAL_DISABILITY,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Ohjattu kuntosaliharjoittelu, Mielenterveysku",
                {EnkoraImporter.SPORT_GYM, EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB},
            ),
            (
                "Ohjattu kuntosaliharjoittelu, Mielenterveyskuntoutujat M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Päiväkotiuinti, Mustikka", {EnkoraImporter.SPORT_SWIM_SCHOOL}),
            ("Pallomylly", set()),
            ("Parkour", {EnkoraImporter.SPORT_PARKOUR}),
            (
                "Parkour, akrobatia ja sirkuslajit",
                {
                    EnkoraImporter.SPORT_PARKOUR,
                    EnkoraImporter.SPORT_ACROBATICS,
                    EnkoraImporter.SPORT_CIRCUS,
                },
            ),
            ("Perhehulinat", set()),
            ("Perheliikunta 2-3 -vuotiaat", set()),
            ("Perhepalloilu", set()),
            ("Pilates", {EnkoraImporter.SPORT_YOGA}),
            ("Porrastreeni", {EnkoraImporter.SPORT_WORKOUT_STAIRS}),
            ("PUISTOJUMPPA", {EnkoraImporter.SPORT_OUTDOOR_PE}),
            ("PUISTOJUMPPA (Kansallismuseo)", {EnkoraImporter.SPORT_OUTDOOR_PE}),
            (
                "PUISTOJUMPPA (Mellunmäen virkistysalue)",
                {EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "Puistojumppa ja kävely",
                {EnkoraImporter.SPORT_OUTDOOR_PE, EnkoraImporter.SPORT_WALKING},
            ),
            (
                "Puistojumppa ja sauvakävely",
                {EnkoraImporter.SPORT_OUTDOOR_PE, EnkoraImporter.SPORT_NORDIC_WALKING},
            ),
            ("Redi", set()),
            (
                "Säestetty jumppa (kevyt) M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Säestetty jumppa M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Sauvakävely", {EnkoraImporter.SPORT_NORDIC_WALKING}),
            (
                "SENIORI VESIJUMPPA, MIEHET JA NAISET",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SENIORI VESIJUMPPA, NAISET",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriCircuit",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_GYM},
            ),
            (
                "SenioriCircuit M + N",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriCircuit N+M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriCore",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_GYM},
            ),
            (
                "SenioriCore N+M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriCore Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriCore+Venyttely",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.SPORT_STRETCHING,
                },
            ),
            (
                "SenioriJumppa Miehet",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                },
            ),
            (
                "SenioriJumppa Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriKahvakuula",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_KETTLEBELL},
            ),
            (
                "SenioriKehonhuolto",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_GYM},
            ),
            (
                "SenioriKeppijumppa",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_BROOMSTICK},
            ),
            (
                "SenioriKevytjumppa N + M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriKuntojumppa",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_JUMPPA},
            ),
            (
                "SenioriKuntojumppa Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriKuntokävely",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_WALKING},
            ),
            (
                "SenioriKuntokävelyTreeni",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_WALKING},
            ),
            (
                "Seniorikuntosalistartti",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_GYM},
            ),
            (
                "SenioriKuntotanssi",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_DANCE},
            ),
            (
                "SenioriKuntotanssi Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriLattarijumppa",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_DANCE},
            ),
            (
                "Seniorilattarijumppa Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriLattarijumppa, Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriLattarit",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_DANCE},
            ),
            (
                "SenioriLattarit Naiset",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Senioriltanssi vasta-alkajille M + N",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriPorrastreeni",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_WORKOUT_STAIRS},
            ),
            ("SenioriSäestys", {EnkoraImporter.AUDIENCE_SENIORS}),
            (
                "SenioriSäestys N + M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriSäestys N+M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Seniorisäpinät", {EnkoraImporter.AUDIENCE_SENIORS}),
            (
                "SenioriSauvakävely",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_NORDIC_WALKING},
            ),
            (
                "SenioriSyke",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.AUDIENCE_SENIORS},
            ),
            (
                "SenioriSyke M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriTanssi M + N",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Senioritanssi vasta-alkajille M + N",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_DANCE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriTanssillinenSyke",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_DANCE},
            ),
            ("SenioriTeema", {EnkoraImporter.AUDIENCE_SENIORS}),
            (
                "SenioriUlkojumppa",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "SenioriUlkoliikunta",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "SenioriUlkotreeni",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "SenioriUlkovoima",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "SenioriuUlkojumppa",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "SenioriuUlkoliikunta",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_OUTDOOR_PE},
            ),
            (
                "SenioriVenytely",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_STRETCHING},
            ),
            (
                "SenioriVenyttely",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_STRETCHING},
            ),
            (
                "SenioriVenyttely M + N",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_STRETCHING,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriVenyttely N + M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_STRETCHING,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "SenioriVKehonhuolto",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_GYM},
            ),
            (
                "SenioriVoima",
                {EnkoraImporter.AUDIENCE_SENIORS, EnkoraImporter.SPORT_GYM},
            ),
            (
                "SenioriVoima N+M",
                {
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Showjazz", {EnkoraImporter.SPORT_DANCE}),
            (
                "Stolgymnastik",
                {EnkoraImporter.SPORT_CHAIR_PE, EnkoraImporter.LANGUAGE_SWEDISH},
            ),
            ("Stretching", {EnkoraImporter.SPORT_STRETCHING}),
            ("Sunnuntaijumppa", {EnkoraImporter.SPORT_JUMPPA}),
            ("Syke", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "Syke (tanssillinen)",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.SPORT_DANCE},
            ),
            ("Syke/Core", {EnkoraImporter.SPORT_GYM, EnkoraImporter.SPORT_JUMPPA}),
            (
                "SYVÄNVEDEN JUMPPA",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.SPORT_JUMPPA},
            ),
            (
                "Syvänveden jumppa M +N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Syvänveden jumppa Naiset",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Syvänvedenvesijumppa  M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Tanssillinen syke",
                {EnkoraImporter.SPORT_JUMPPA, EnkoraImporter.SPORT_DANCE},
            ),
            ("Tasapaino ja core", {EnkoraImporter.SPORT_GYM}),
            ("Tasapaino- ja voimaharjoittelu", {EnkoraImporter.SPORT_GYM}),
            (
                "Tasapaino- ja voimaharjoittelu M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Teema", set()),
            (
                "Teema M + N",
                {EnkoraImporter.AUDIENCE_MEN, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            ("TEKNIIKKA", set()),
            ("TEKNIIKKA 1, työikäiset", {EnkoraImporter.AUDIENCE_WORKING_AGE}),
            ("TEKNIIKKA 1, yli 7 -VUOTIAAT", set()),
            ("TEKNIIKKA, Työikäiset", {EnkoraImporter.AUDIENCE_WORKING_AGE}),
            ("Temppuhulinat 2-6 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa 3-4 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa 4-5 vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa 4-5 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa 5-6 vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa 5-6 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa 7-9 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Temppujumppa perheet 2-6 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("Tempputaito 5-6 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("TemppuTaito 7-8 -vuotiaat", {EnkoraImporter.SPORT_JUMPPA}),
            ("testikurssi", set()),
            ("TUOLIJUMPPA", {EnkoraImporter.SPORT_CHAIR_PE}),
            (
                "Tuolijumppa M + N",
                {
                    EnkoraImporter.SPORT_CHAIR_PE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Tuolijumppa N+M",
                {
                    EnkoraImporter.SPORT_CHAIR_PE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Tuolijumppa Naiset",
                {EnkoraImporter.SPORT_CHAIR_PE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "TYTTÖJEN UIMAKOULU, ALKEET 10 - 12 -VUOTIAAT",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "TYTTÖJEN UIMAKOULU, ALKEET 10 - 16 -VUOTIAAT",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "TYTTÖJEN UIMAKOULU, ALKEET 10-16 -vuotiaat",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "TYTTÖJEN UIMAKOULU, ALKEET 7-9 -vuotiaat",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "TYTTÖJEN UIMAKOULU, ALKEET yli 6 -vuotiaat",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            ("TYTTÖJEN UIMAKOULU, JATKO", {EnkoraImporter.SPORT_SWIM_SCHOOL}),
            ("TYTTÖJEN UIMAKOULU, JATKO 1", {EnkoraImporter.SPORT_SWIM_SCHOOL}),
            (
                "TYTTÖJEN UIMAKOULU, JATKO 1 yli 6 -vuotiaat",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "TYTTÖJEN UIMAKOULU, JATKO 1 yli 6 -vuotiaat (10m uimataito vaaditaan)",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            (
                "TYTTÖJEN UIMAKOULU, TEKNIIKKA yli 6 -vuotiaat",
                {EnkoraImporter.SPORT_SWIM_SCHOOL},
            ),
            ("UINTITEKNIIKKA", {EnkoraImporter.SPORT_SWIM_SCHOOL}),
            ("Ulkokuntosalistartti", {EnkoraImporter.SPORT_OUTDOOR_PE}),
            (
                "Ulkoliikunta Mielenterveyskuntoutujat",
                {
                    EnkoraImporter.SPORT_OUTDOOR_PE,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                },
            ),
            ("Ulkoliikunta, Länsi", {EnkoraImporter.SPORT_OUTDOOR_PE}),
            ("UlkoTreeni", {EnkoraImporter.SPORT_OUTDOOR_PE}),
            ("UlkoVoima", {EnkoraImporter.SPORT_OUTDOOR_PE, EnkoraImporter.SPORT_GYM}),
            (
                "Uteträning för seniorer",
                {
                    EnkoraImporter.SPORT_OUTDOOR_PE,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.AUDIENCE_SENIORS,
                },
            ),
            (
                "Vattengymnastik D + H",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vattengymnastik, D",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vattengymnastik, Damer",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vattengymnastik, Krigsveteraner D +  H",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.LANGUAGE_SWEDISH,
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Venyttely", {EnkoraImporter.SPORT_STRETCHING}),
            ("Venyttely ja rentoutus", {EnkoraImporter.SPORT_STRETCHING}),
            (
                "Venyttely ja rentoutus, Mielenterveyskuntoutu",
                {
                    EnkoraImporter.SPORT_STRETCHING,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                },
            ),
            (
                "Venyttely ja rentoutus, Mielenterveyskuntoutujat M + N",
                {
                    EnkoraImporter.SPORT_STRETCHING,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Venyttely M + N",
                {
                    EnkoraImporter.SPORT_STRETCHING,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Vesijumppa", {EnkoraImporter.SPORT_WATER_EXERCISE}),
            (
                "Vesijumppa  M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa +75 ja veteraanit",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_SENIORS},
            ),
            (
                "Vesijumppa +75 ja veteraanit, M+N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "VESIJUMPPA +75 -vuotiaat, NAISET",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "Vesijumppa M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa M + N, AVH",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa M+N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa Miehet",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_MEN},
            ),
            (
                "Vesijumppa N",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "Vesijumppa N+M",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa Naiset",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "Vesijumppa Naiset 75+",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa syöpään sairastuneille M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa,  M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, Aivohalvaantuneet M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, Kehitysvammaiset M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_INTELLECTUAL_DISABILITY,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, Kuulovammaiset ja huonokuuloiset ",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_HEARING_IMPAIRED,
                },
            ),
            (
                "Vesijumppa, M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, Miehet",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_MEN},
            ),
            (
                "VESIJUMPPA, MIEHET JA NAISET",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, Mielenterveyskuntoutujat M",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                    EnkoraImporter.AUDIENCE_MEN,
                },
            ),
            (
                "Vesijumppa, Mielenterveyskuntoutujat M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, Mielenterveyskuntoutujat Naiset",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_PSYCHIATRIC_REHAB,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "VESIJUMPPA, N+M",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "VESIJUMPPA, NAISET",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "Vesijumppa, Neurologiset asiakkaat M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, syöpään sairastuneille, M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "Vesijumppa, veteraani M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_SENIORS,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Vesijuoksu", {EnkoraImporter.SPORT_WATER_EXERCISE}),
            ("Vesitreeni", {EnkoraImporter.SPORT_WATER_EXERCISE}),
            ("Voima", {EnkoraImporter.SPORT_GYM}),
            (
                "Voima M + N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("Voimajumppa", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "XXL -vesijumppa -ryhmä M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "XXL -vesijumppa -ryhmä Naiset",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
            (
                "XXL_kuntosaliharjoittelu M+N",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("XXL-jumppa", {EnkoraImporter.SPORT_JUMPPA}),
            (
                "XXL-jumppa M + N",
                {
                    EnkoraImporter.SPORT_JUMPPA,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "XXL-kuntosaliharjoittelu N+M",
                {
                    EnkoraImporter.SPORT_GYM,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            ("XXL-startti", set()),
            ("XXL-stratti", set()),
            (
                "XXL-vesijumppa M + N",
                {
                    EnkoraImporter.SPORT_WATER_EXERCISE,
                    EnkoraImporter.AUDIENCE_MEN,
                    EnkoraImporter.AUDIENCE_WOMEN,
                },
            ),
            (
                "XXL-vesijumppa Naiset",
                {EnkoraImporter.SPORT_WATER_EXERCISE, EnkoraImporter.AUDIENCE_WOMEN},
            ),
        ],
    )
    def test_parse_keywords_returns_correct_result(
        self, test_input_descriptions, expected_keywords
    ):
        assert (
            EnkoraImporter._parse_description_keywords(test_input_descriptions)
            == expected_keywords
        )
