# Generated by Django 2.2.13 on 2021-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=18),
        ),
    ]
