# Generated by Django 2.2.13 on 2021-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0003_auto_20211125_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="phone_number",
            field=models.CharField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
