# Generated by Django 2.2.13 on 2021-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0006_auto_20211126_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="attendee_status",
            field=models.CharField(
                choices=[("waitlisted", "Waitlisted"), ("attending", "Attending")],
                default="attending",
                max_length=25,
                verbose_name="Attendee status",
            ),
        ),
    ]
