# Generated by Django 2.2.13 on 2021-12-01 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0009_auto_20211201_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="street_address",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Street address",
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="zipcode",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="Street address",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="native_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signup_native_language",
                to="events.Language",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="service_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signup_service_language",
                to="events.Language",
            ),
        ),
    ]
