# Generated by Django 3.2.18 on 2023-04-24 13:55

from django.db import migrations, models

import registrations.models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0011_seatreservationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="mandatory_fields",
            field=registrations.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("city", "City"),
                        ("name", "Name"),
                        ("phone_number", "Phone number"),
                        ("street_address", "Street address"),
                        ("zipcode", "ZIP code"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Mandatory fields",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="waiting_list_capacity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Waiting list capacity"
            ),
        ),
        migrations.AlterField(
            model_name="seatreservationcode",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="signup",
            name="city",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="extra_info",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Extra info"
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="membership_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Membership number",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="zipcode",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="ZIP code",
            ),
        ),
    ]
