# Generated by Django 3.2.18 on 2023-04-05 12:12

from django.db import migrations, models

from registrations.models import MandatoryField


def create_initial_mandatory_fields(apps, schema_editor):
    MandatoryField.objects.create(
        id=MandatoryField.DefaultMandatoryField.NAME,
    )

    MandatoryField.objects.create(
        id=MandatoryField.DefaultMandatoryField.CITY,
    )

    MandatoryField.objects.create(
        id=MandatoryField.DefaultMandatoryField.ZIPCODE,
    )

    MandatoryField.objects.create(
        id=MandatoryField.DefaultMandatoryField.STREET_ADDRESS,
    )

    MandatoryField.objects.create(
        id=MandatoryField.DefaultMandatoryField.PHONE_NUMBER,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0011_seatreservationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MandatoryField",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="registration",
            name="mandatory_fields",
            field=models.ManyToManyField(
                blank=True,
                to="registrations.MandatoryField",
                verbose_name="Mandatory fields",
            ),
        ),
        migrations.RunPython(
            code=create_initial_mandatory_fields,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
