# Generated by Django 3.2.18 on 2023-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0013_alter_registration_waiting_list_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Name"),
        ),
    ]
