# Generated by Django 3.2.18 on 2023-05-30 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0013_alter_signup_registration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="signup",
            unique_together=set(),
        ),
    ]
