# Generated by Django 3.2.18 on 2023-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0014_alter_signup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatreservationcode",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
        ),
    ]
