# Generated by Django 3.2.18 on 2023-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0014_alter_signup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
    ]
