# Generated by Django 3.2.19 on 2023-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0014_alter_signup_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="confirmation_message_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Confirmation message"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="confirmation_message_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Confirmation message"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="confirmation_message_fi",
            field=models.TextField(
                blank=True, null=True, verbose_name="Confirmation message"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="confirmation_message_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Confirmation message"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="confirmation_message_sv",
            field=models.TextField(
                blank=True, null=True, verbose_name="Confirmation message"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="confirmation_message_zh_hans",
            field=models.TextField(
                blank=True, null=True, verbose_name="Confirmation message"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="instructions_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Instructions"),
        ),
        migrations.AddField(
            model_name="registration",
            name="instructions_en",
            field=models.TextField(blank=True, null=True, verbose_name="Instructions"),
        ),
        migrations.AddField(
            model_name="registration",
            name="instructions_fi",
            field=models.TextField(blank=True, null=True, verbose_name="Instructions"),
        ),
        migrations.AddField(
            model_name="registration",
            name="instructions_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Instructions"),
        ),
        migrations.AddField(
            model_name="registration",
            name="instructions_sv",
            field=models.TextField(blank=True, null=True, verbose_name="Instructions"),
        ),
        migrations.AddField(
            model_name="registration",
            name="instructions_zh_hans",
            field=models.TextField(blank=True, null=True, verbose_name="Instructions"),
        ),
    ]
