# Generated by Django 3.2.19 on 2023-08-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0016_multilingual_confirmation_message_and_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_users",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "unique_together": {("email", "registration")},
            },
        ),
    ]
