# Generated by Django 3.2.19 on 2023-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0019_alter_registration_mandatory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="presence_status",
            field=models.CharField(
                choices=[("not_present", "Not present"), ("present", "Present")],
                default="not_present",
                max_length=25,
                verbose_name="Presence status",
            ),
        ),
    ]
