# Generated by Django 3.2.20 on 2023-08-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0094_remove_image_alt_text_translations"),
        ("registrations", "0020_signup_presence_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationUserAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_user_access_language",
                        to="events.language",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_user_accesses",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "unique_together": {("email", "registration")},
            },
        ),
    ]
