# Generated by Django 3.2.20 on 2023-08-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0093_increase_provider_contact_info_max_length"),
        ("registrations", "0020_registrationuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationuser",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registration_user_language",
                to="events.language",
            ),
        ),
    ]
