# Generated by Django 3.2.20 on 2023-08-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0093_increase_provider_contact_info_max_length"),
        ("registrations", "0021_registrationuser_language"),
    ]

    operations = [
        migrations.RenameModel("RegistrationUser", "RegistrationUserAccess"),
        migrations.AlterField(
            model_name="registrationuseraccess",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registration_user_access_language",
                to="events.language",
            ),
        ),
        migrations.AlterField(
            model_name="registrationuseraccess",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_user_accesses",
                to="registrations.registration",
            ),
        ),
    ]
