# Generated by Django 3.2.20 on 2023-08-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import registrations.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registrations", "0021_registrationuseraccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="responsible_for_group",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SignUpGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Extra info"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signup_groups",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, registrations.models.SignUpMixin),
        ),
        migrations.AddField(
            model_name="signup",
            name="signup_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signups",
                to="registrations.signupgroup",
            ),
        ),
    ]
