# Generated by Django 3.2.20 on 2023-09-22 12:26

import encrypted_fields.fields
from django.db import migrations, models
from django.db.models import Q, deletion


def forwards_func(apps, schema_editor):
    signup_group_model = apps.get_model("registrations", "SignUpGroup")
    signup_group_protected_model = apps.get_model(
        "registrations", "SignUpGroupProtectedData"
    )

    signup_group_protected_datas = []
    for signup_group in signup_group_model.objects.filter(
        Q(extra_info__isnull=False) & ~Q(extra_info__exact="")
    ).only("id", "registration", "extra_info"):
        signup_group_protected_datas.append(
            signup_group_protected_model(
                registration=signup_group.registration,
                signup_group=signup_group,
                extra_info=signup_group.extra_info,
            )
        )
    signup_group_protected_model.objects.bulk_create(signup_group_protected_datas)

    signup_model = apps.get_model("registrations", "SignUp")
    signup_protected_model = apps.get_model("registrations", "SignUpProtectedData")

    signup_protected_datas = []
    for signup in signup_model.objects.filter(
        Q(extra_info__isnull=False) & ~Q(extra_info__exact="")
        | Q(date_of_birth__isnull=False)
    ).only("id", "registration", "extra_info", "date_of_birth"):
        signup_protected_datas.append(
            signup_protected_model(
                registration=signup.registration,
                signup=signup,
                extra_info=signup.extra_info,
                date_of_birth=signup.date_of_birth,
            )
        )
    signup_protected_model.objects.bulk_create(signup_protected_datas)


def backwards_func(apps, schema_editor):
    signup_group_model = apps.get_model("registrations", "SignUpGroup")
    signup_model = apps.get_model("registrations", "SignUp")

    for signup_group in signup_group_model.objects.filter(
        protected_data__isnull=False
    ).select_related("protected_data"):
        signup_group.extra_info = signup_group.protected_data.extra_info
        signup_group.save(update_fields=["extra_info"])

    for signup in signup_model.objects.filter(
        protected_data__isnull=False
    ).select_related("protected_data"):
        signup.extra_info = signup.protected_data.extra_info
        signup.date_of_birth = signup.protected_data.date_of_birth
        signup.save(update_fields=["extra_info", "date_of_birth"])


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0023_rename_timestamp_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignUpProtectedData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_info",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True, default=None, null=True, verbose_name="Extra info"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=deletion.PROTECT,
                        related_name="%(class)s",
                        to="registrations.registration",
                    ),
                ),
                (
                    "date_of_birth",
                    encrypted_fields.fields.EncryptedDateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "signup",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=deletion.SET_NULL,
                        related_name="protected_data",
                        to="registrations.signup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignUpGroupProtectedData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_info",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True, default=None, null=True, verbose_name="Extra info"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=deletion.PROTECT,
                        related_name="%(class)s",
                        to="registrations.registration",
                    ),
                ),
                (
                    "signup_group",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=deletion.SET_NULL,
                        related_name="protected_data",
                        to="registrations.signupgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name="signup",
            name="extra_info",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="signupgroup",
            name="extra_info",
        ),
    ]
