# Generated by Django 3.2.22 on 2023-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0024_signup_and_signup_group_protected_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="user_consent",
            field=models.BooleanField(default=False, verbose_name="User consent"),
        ),
    ]
