# Generated by Django 3.2.22 on 2023-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0025_signup_user_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="pseudonymization_time",
            field=models.DateTimeField(null=True, verbose_name="Pseudonymization time"),
        ),
        migrations.AddField(
            model_name="signupgroup",
            name="pseudonymization_time",
            field=models.DateTimeField(null=True, verbose_name="Pseudonymization time"),
        ),
    ]
