# Generated by Django 3.2.22 on 2023-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0025_signup_user_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="attendee_status",
            field=models.CharField(
                choices=[("waitlisted", "Waitlisted"), ("attending", "Attending")],
                db_index=True,
                default="attending",
                max_length=25,
                verbose_name="Attendee status",
            ),
        ),
        migrations.AddConstraint(
            model_name="seatreservationcode",
            constraint=models.UniqueConstraint(
                fields=("registration", "code"), name="unique_seat_reservation"
            ),
        ),
    ]
