# Generated by Django 3.2.23 on 2023-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0027_signup_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="anonymization_time",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Anonymization time"
            ),
        ),
        migrations.AddField(
            model_name="signupgroup",
            name="anonymization_time",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Anonymization time"
            ),
        ),
    ]
