# Generated by Django 3.2.22 on 2023-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0027_signup_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="anonymization_time",
            field=models.DateTimeField(null=True, verbose_name="Anonymization time"),
        ),
        migrations.AddField(
            model_name="signupgroup",
            name="anonymization_time",
            field=models.DateTimeField(null=True, verbose_name="Anonymization time"),
        ),
    ]
