# Generated by Django 3.2.23 on 2023-12-05 14:47

from django.db import migrations, models

import registrations.models


def remove_phone_number_from_mandatory_fields(apps, schema_editor):
    Registration = apps.get_model("registrations", "Registration")

    registrations_to_be_update = []
    registrations = Registration.objects.filter(
        mandatory_fields__contains=["phone_number"]
    )

    for registration in registrations:
        # Remove phone_number from mandatory fields
        registration.mandatory_fields.remove("phone_number")
        registrations_to_be_update.append(registration)

    Registration.objects.bulk_update(registrations_to_be_update, ["mandatory_fields"])


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0028_signup_anonymization_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="mandatory_fields",
            field=registrations.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("city", "City"),
                        ("first_name", "First name"),
                        ("last_name", "Last name"),
                        ("street_address", "Street address"),
                        ("zipcode", "ZIP code"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Mandatory fields",
            ),
        ),
        migrations.RunPython(
            remove_phone_number_from_mandatory_fields, migrations.RunPython.noop
        ),
    ]
