# Generated by Django 3.2.23 on 2023-12-11 15:13

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0029_alter_registration_mandatory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="contact_person_mandatory_fields",
            field=registrations.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("phone_number", "Phone number")],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Mandatory fields of contact person",
            ),
        ),
    ]
