# Generated by Django 3.2.23 on 2023-12-12 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_orghierarchy", "0011_alter_datasource_user_editable_organizations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registrations", "0029_alter_registration_mandatory_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationPriceGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                ("description", models.CharField(max_length=255)),
                ("description_fi", models.CharField(max_length=255, null=True)),
                ("description_sv", models.CharField(max_length=255, null=True)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("description_zh_hans", models.CharField(max_length=255, null=True)),
                ("description_ru", models.CharField(max_length=255, null=True)),
                ("description_ar", models.CharField(max_length=255, null=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrationpricegroup_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrationpricegroup_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_price_groups",
                        to="django_orghierarchy.organization",
                        verbose_name="Publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignUpPriceGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("description_fi", models.CharField(max_length=255, null=True)),
                ("description_sv", models.CharField(max_length=255, null=True)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("description_zh_hans", models.CharField(max_length=255, null=True)),
                ("description_ru", models.CharField(max_length=255, null=True)),
                ("description_ar", models.CharField(max_length=255, null=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "registration_price_group",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_price_group",
                        to="registrations.registrationpricegroup",
                    ),
                ),
                (
                    "signup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_group",
                        to="registrations.signup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
