# Generated by Django 4.2.11 on 2024-03-15 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_orghierarchy", "0011_alter_datasource_user_editable_organizations"),
        ("registrations", "0039_offer_price_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebStoreMerchant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Is active")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "street_address",
                    models.CharField(max_length=500, verbose_name="Street address"),
                ),
                ("zipcode", models.CharField(max_length=10, verbose_name="ZIP code")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone_number",
                    models.CharField(max_length=18, verbose_name="Phone number"),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "terms_of_service_url",
                    models.URLField(verbose_name="Terms of Service URL"),
                ),
                (
                    "business_id",
                    models.CharField(max_length=9, verbose_name="Business ID"),
                ),
                (
                    "paytrail_merchant_id",
                    models.CharField(
                        max_length=100, verbose_name="Paytrail merchant ID"
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_store_merchants",
                        to="django_orghierarchy.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
