# Generated by Django 4.2.11 on 2024-03-20 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_orghierarchy", "0011_alter_datasource_user_editable_organizations"),
        ("registrations", "0040_webstoremerchant"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebStoreAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Is active")),
                ("vat_code", models.CharField(max_length=2, verbose_name="VAT code")),
                (
                    "company_code",
                    models.CharField(max_length=4, verbose_name="SAP company code"),
                ),
                (
                    "main_ledger_account",
                    models.CharField(max_length=6, verbose_name="Main ledger account"),
                ),
                (
                    "balance_profit_center",
                    models.CharField(
                        max_length=10, verbose_name="Balance profit center"
                    ),
                ),
                (
                    "internal_order",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Internal order",
                    ),
                ),
                (
                    "profit_center",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=7,
                        verbose_name="Profit center",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Project"
                    ),
                ),
                (
                    "operation_area",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=6,
                        verbose_name="SAP functional area",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_store_accounts",
                        to="django_orghierarchy.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
