# Generated by Django 4.2.11 on 2024-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0043_alter_registrationwebstoreproductmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="signuppricegroup",
            name="external_order_item_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
