# Generated by Django 4.2.11 on 2024-05-10 09:30

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def migrate_merchant_ids(apps, schema_editor):
    merchant_model = apps.get_model("registrations", "WebStoreMerchant")
    product_mapping_model = apps.get_model(
        "registrations", "RegistrationWebStoreProductMapping"
    )

    product_mapping_model.objects.all().update(
        external_merchant_id=Subquery(
            merchant_model.objects.filter(pk=OuterRef(OuterRef("merchant_id"))).values(
                "merchant_id"
            )[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0046_alter_webstoremerchant_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationwebstoreproductmapping",
            name="external_merchant_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(migrate_merchant_ids, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="registrationwebstoreproductmapping",
            name="merchant",
        ),
    ]
