# Generated by Django 4.2.11 on 2024-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0047_alter_registrationwebstoreproductmapping_merchant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="webstoreaccount",
            name="name",
            field=models.CharField(
                default="account", max_length=255, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
