# Generated by Django 4.2.13 on 2024-06-07 14:01

import django.db.models.deletion
from django.db import migrations, models

import registrations.models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0050_registration_merchant_and_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="signuppaymentrefund",
            name="external_refund_id",
            field=models.CharField(default="None", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signuppaymentrefund",
            name="signup",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_refund",
                to="registrations.signup",
            ),
        ),
        migrations.AddField(
            model_name="signuppaymentrefund",
            name="signup_group",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_refund",
                to="registrations.signupgroup",
            ),
        ),
        migrations.CreateModel(
            name="SignUpPaymentCancellation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation",
                        to="registrations.signuppayment",
                    ),
                ),
                (
                    "signup",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_cancellation",
                        to="registrations.signup",
                    ),
                ),
                (
                    "signup_group",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_cancellation",
                        to="registrations.signupgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(registrations.models.SignUpOrGroupDependingMixin, models.Model),
        ),
    ]
