# Generated by Django 4.2.13 on 2024-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0051_signuppaymentcancellation_and_external_refund_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="maximum_attendee_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Maximum attendee capacity"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="minimum_attendee_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Minimum attendee capacity"
            ),
        ),
    ]
