# Generated by Django 4.2.13 on 2024-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0052_alter_registration_min_and_max_attendee_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="remaining_attendee_capacity",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="remaining_waiting_list_capacity",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="waiting_list_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Waiting list capacity"
            ),
        ),
    ]
