# Generated by Django 4.2.18 on 2025-01-30 14:11
from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def forward(apps, schema_editor):
    SeatReservationCode = apps.get_model("registrations", "SeatReservationCode")  # noqa: F841 N806
    SeatReservationCode.objects.all().update(
        expiration=F("timestamp")
        + F("seats") * timedelta(minutes=1)
        + timedelta(minutes=settings.SEAT_RESERVATION_DURATION)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0054_new_general_vat_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatreservationcode",
            name="expiration",
            field=models.DateTimeField(
                default=None,
                null=True,
                verbose_name="Expiration time of the reservation",
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="seatreservationcode",
            name="expiration",
            field=models.DateTimeField(
                verbose_name="Expiration time of the reservation"
            ),
        ),
    ]
