# Generated by Django 4.2.18 on 2025-01-30 09:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0054_new_general_vat_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatreservationcode",
            name="expiration_extension",
            field=models.DurationField(
                default=datetime.timedelta(0),
                verbose_name="Duration to extend the expiration time with",
            ),
        ),
    ]
