# Generated by Django 4.2.18 on 2025-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0055_seatreservationcode_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="signuppayment",
            name="expiry_notification_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
