# Generated by Django 5.2.5 on 2025-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0056_signuppayment_expiry_notification_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="price_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="registrations",
                through="registrations.RegistrationPriceGroup",
                through_fields=("registration", "price_group"),
                to="registrations.pricegroup",
            ),
        ),
    ]
