# Generated by Django 5.2.8 on 2025-12-02 05:04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0057_alter_registration_price_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerpricegroup",
            name="vat_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("25.50"), "25.5 %"),
                    (Decimal("14.00"), "14 %"),
                    (Decimal("13.50"), "13.5 %"),
                    (Decimal("10.00"), "10 %"),
                    (Decimal("0.00"), "0 %"),
                ],
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="registrationpricegroup",
            name="vat_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("25.50"), "25.5 %"),
                    (Decimal("14.00"), "14 %"),
                    (Decimal("13.50"), "13.5 %"),
                    (Decimal("10.00"), "10 %"),
                    (Decimal("0.00"), "0 %"),
                ],
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="registrationwebstoreproductmapping",
            name="vat_code",
            field=models.CharField(
                choices=[
                    ("47", "25.5 %"),
                    ("45", "14 %"),
                    ("48", "13.5 %"),
                    ("46", "10 %"),
                    ("4U", "0 %"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="signuppricegroup",
            name="vat_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("25.50"), "25.5 %"),
                    (Decimal("14.00"), "14 %"),
                    (Decimal("13.50"), "13.5 %"),
                    (Decimal("10.00"), "10 %"),
                    (Decimal("0.00"), "0 %"),
                ],
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=4,
            ),
        ),
    ]
