# Generated by Django 5.2.9 on 2026-01-21 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import registrations.models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0058_alter_offerpricegroup_vat_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricegroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricegroup",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="pricegroup",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricegroup",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="attendee_registration",
            field=models.BooleanField(
                default=False, help_text="Whether attendee registration is enabled."
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="audience_max_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Maximum age of attendees.",
                null=True,
                verbose_name="Maximum recommended age",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="audience_min_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Minimum age of attendees.",
                null=True,
                verbose_name="Minimum recommended age",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="enrolment_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when enrolment for the event ends.",
                null=True,
                verbose_name="Enrollment end time",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="enrolment_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when enrolment for the event starts.",
                null=True,
                verbose_name="Enrollment start time",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="mandatory_fields",
            field=registrations.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("city", "City"),
                        ("first_name", "First name"),
                        ("last_name", "Last name"),
                        ("phone_number", "Phone number"),
                        ("street_address", "Street address"),
                        ("zipcode", "ZIP code"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                help_text="Mandatory fields in the enrolment form.",
                size=None,
                verbose_name="Mandatory fields",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="maximum_attendee_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of attendees allowed for the event.",
                null=True,
                verbose_name="Maximum attendee capacity",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="maximum_group_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Maximum number of attendees allowed in a single group.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Maximum group size",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="minimum_attendee_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum number of attendees required for the event to take place.",
                null=True,
                verbose_name="Minimum attendee capacity",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="waiting_list_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of people allowed to register to the waiting list.",
                null=True,
                verbose_name="Waiting list capacity",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
        migrations.AlterField(
            model_name="signupgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signupgroup",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="signupgroup",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signupgroup",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
        migrations.AlterField(
            model_name="signuppayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signuppayment",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="signuppayment",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signuppayment",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
        migrations.AlterField(
            model_name="webstoreaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webstoreaccount",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="webstoreaccount",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webstoreaccount",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
        migrations.AlterField(
            model_name="webstoremerchant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that created this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webstoremerchant",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="webstoremerchant",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that last modified this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webstoremerchant",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when last modified.",
                verbose_name="Modified at",
            ),
        ),
    ]
