# Generated by Django 5.2.11 on 2026-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0058_alter_offerpricegroup_vat_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="attendee_status",
            field=models.CharField(
                choices=[
                    ("waitlisted", "Waitlisted"),
                    ("attending", "Attending"),
                    ("awaiting_payment", "Awaiting payment"),
                ],
                db_index=True,
                default="attending",
                max_length=25,
                verbose_name="Attendee status",
            ),
        ),
    ]
