# Generated by Django 5.2.11 on 2026-02-26 21:02

from django.db import migrations
from django.db.models import Q


def set_awaiting_payment_attendee_status(apps, schema_editor):
    """Set attendee status from "attending" to "awaiting_payment" for SignUps which have
    an unpaid payment attached to them."""
    Signup = apps.get_model("registrations", "Signup")
    Signup.objects.filter(attendee_status="attending").filter(
        Q(payment__status="created") | Q(signup_group__payment__status="created")
    ).update(attendee_status="awaiting_payment")


def reverse_set_awaiting_payment_attendee_status(apps, schema_editor):
    """Revert the attendee_status from "awaiting_payment" back to "attending" for SignUps."""
    Signup = apps.get_model("registrations", "Signup")
    Signup.objects.filter(attendee_status="awaiting_payment").update(
        attendee_status="attending"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0059_alter_signup_attendee_status"),
    ]

    operations = [
        migrations.RunPython(
            set_awaiting_payment_attendee_status,
            reverse_set_awaiting_payment_attendee_status,
        ),
    ]
