# Generated by Django 5.2.13 on 2026-05-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0061_alter_pricegroup_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signuppricegroup",
            name="registration_price_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signup_price_groups",
                to="registrations.registrationpricegroup",
            ),
        ),
    ]
