# Generated by Django 2.2.9 on 2020-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unpublished_event_deleted', 'Unpublished event deleted'), ('event_published', 'Event published'), ('draft_posted', 'Draft posted')], db_index=True, max_length=100, unique=True, verbose_name='Type')),
                ('subject', models.CharField(help_text='Subject for email notifications', max_length=200, verbose_name='Subject')),
                ('subject_fi', models.CharField(help_text='Subject for email notifications', max_length=200, null=True, verbose_name='Subject')),
                ('subject_sv', models.CharField(help_text='Subject for email notifications', max_length=200, null=True, verbose_name='Subject')),
                ('subject_en', models.CharField(help_text='Subject for email notifications', max_length=200, null=True, verbose_name='Subject')),
                ('subject_zh_hans', models.CharField(help_text='Subject for email notifications', max_length=200, null=True, verbose_name='Subject')),
                ('subject_ru', models.CharField(help_text='Subject for email notifications', max_length=200, null=True, verbose_name='Subject')),
                ('subject_ar', models.CharField(help_text='Subject for email notifications', max_length=200, null=True, verbose_name='Subject')),
                ('body', models.TextField(blank=True, help_text='Text body for email notifications', verbose_name='Body')),
                ('body_fi', models.TextField(blank=True, help_text='Text body for email notifications', null=True, verbose_name='Body')),
                ('body_sv', models.TextField(blank=True, help_text='Text body for email notifications', null=True, verbose_name='Body')),
                ('body_en', models.TextField(blank=True, help_text='Text body for email notifications', null=True, verbose_name='Body')),
                ('body_zh_hans', models.TextField(blank=True, help_text='Text body for email notifications', null=True, verbose_name='Body')),
                ('body_ru', models.TextField(blank=True, help_text='Text body for email notifications', null=True, verbose_name='Body')),
                ('body_ar', models.TextField(blank=True, help_text='Text body for email notifications', null=True, verbose_name='Body')),
                ('html_body', models.TextField(blank=True, help_text='HTML body for email notifications', verbose_name='HTML Body')),
                ('html_body_fi', models.TextField(blank=True, help_text='HTML body for email notifications', null=True, verbose_name='HTML Body')),
                ('html_body_sv', models.TextField(blank=True, help_text='HTML body for email notifications', null=True, verbose_name='HTML Body')),
                ('html_body_en', models.TextField(blank=True, help_text='HTML body for email notifications', null=True, verbose_name='HTML Body')),
                ('html_body_zh_hans', models.TextField(blank=True, help_text='HTML body for email notifications', null=True, verbose_name='HTML Body')),
                ('html_body_ru', models.TextField(blank=True, help_text='HTML body for email notifications', null=True, verbose_name='HTML Body')),
                ('html_body_ar', models.TextField(blank=True, help_text='HTML body for email notifications', null=True, verbose_name='HTML Body')),
            ],
            options={
                'verbose_name': 'Notification template',
                'verbose_name_plural': 'Notification templates',
            },
        ),
    ]
