# Generated by Django 2.2.28 on 2024-03-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20240215_1520'),
        ('notifications', '0004_auto_20231212_1048'),
    ]

    operations = [
    ]
