name: 'Debendabot alerts to slack'

on:
  schedule:
    - cron: '10 08 * * 1' # at 10:10 (gmt+2) / 11:10 (gmt+3) every Monday.

jobs:
  dependabot-alerts-to-slack:
    runs-on: ubuntu-latest
    steps:
      # v1.7.18 - Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - uses: kunalnagarco/action-cve@91ea7598d2ec2765d41e4d9f999a632ed7982ee8
        with:
          # espooevents-ci user token
          token: ${{ secrets.ESPOOEVENTS_ACCESS_TOKEN }}
          slack_webhook: ${{ secrets.ESPOOEVENTS_SLACK_WEBHOOK }}
          # Maximum that you can send to slack due message size limit.
          count: 30
